"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

import {
  ArrowUpRight,
  Bot,
  CheckCircle2,
  ChevronRight,
  FileText,
  Globe,
  Image,
  MessageSquare,
  MoreHorizontal,
  Pause,
  Pencil,
  Play,
  Plus,
  Trash2,
  TrendingUp,
  Workflow,
  Zap,
} from "lucide-react";

import AIWidget from "@/components/dashboard/AIWidget";

type DashboardStats = {
  aiEmployees: {
    total: number;
    running: number;
    paused: number;
    offline: number;
  };

  automations: {
    total: number;
    running: number;
    paused: number;
    draft: number;
    error: number;
    runs: number;
  };

  tasksCompleted: number;
  revenueGenerated: number;
};

type ActivityItem = {
  id: string;
  action: string;
  entity_type: string;
  entity_id: string | null;
  title: string;
  description: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
};

const quickActions = [
  {
    title: "AI Employee",
    description: "Create an intelligent employee",
    icon: Bot,
    href: "/dashboard/ai-employees",
    status: "ready" as const,
  },
  {
    title: "Workflow",
    description: "Automate a business process",
    icon: Workflow,
    href: "/dashboard/automation/flow",
    status: "ready" as const,
  },
  {
    title: "Website",
    description: "Scheduled for the product sprint",
    icon: Globe,
    href: null,
    status: "building" as const,
  },
  {
    title: "WhatsApp Bot",
    description: "Connect your business",
    icon: MessageSquare,
    href: "/dashboard/whatsapp",
    status: "ready" as const,
  },
  {
    title: "Generate Images",
    description: "Scheduled for AI Studio",
    icon: Image,
    href: null,
    status: "building" as const,
  },
  {
    title: "Upload Documents",
    description: "Scheduled for Knowledge Hub",
    icon: FileText,
    href: null,
    status: "building" as const,
  },
];

export default function Overview({
  userName,
}: {
  userName: string;
}) {
  const [dashboardStats, setDashboardStats] =
    useState<DashboardStats>({
      aiEmployees: {
        total: 0,
        running: 0,
        paused: 0,
        offline: 0,
      },

      automations: {
        total: 0,
        running: 0,
        paused: 0,
        draft: 0,
        error: 0,
        runs: 0,
      },

      tasksCompleted: 0,
      revenueGenerated: 0,
    });

  const [statsLoading, setStatsLoading] =
    useState(true);

  const [activity, setActivity] =
    useState<ActivityItem[]>([]);

  const [activityLoading, setActivityLoading] =
    useState(true);

  const [createOpen, setCreateOpen] =
    useState(false);

  useEffect(() => {
    let cancelled = false;

    async function loadDashboardStats() {
      try {
        const response = await fetch(
          "/api/dashboard/stats",
          {
            method: "GET",
            cache: "no-store",
          }
        );

        if (!response.ok) {
          throw new Error(
            "Could not load dashboard stats."
          );
        }

        const data = await response.json();

        if (
          !cancelled &&
          data.success &&
          data.stats
        ) {
          setDashboardStats(data.stats);
        }
      } catch (error) {
        console.error(
          "Dashboard stats error:",
          error
        );
      } finally {
        if (!cancelled) {
          setStatsLoading(false);
        }
      }
    }

    loadDashboardStats();

    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    let cancelled = false;

    async function loadActivity() {
      try {
        const response = await fetch(
          "/api/dashboard/activity",
          {
            method: "GET",
            cache: "no-store",
          }
        );

        if (!response.ok) {
          throw new Error(
            "Could not load recent activity."
          );
        }

        const data = await response.json();

        if (
          !cancelled &&
          data.success &&
          Array.isArray(data.activity)
        ) {
          setActivity(data.activity);
        }
      } catch (error) {
        console.error(
          "Dashboard activity error:",
          error
        );
      } finally {
        if (!cancelled) {
          setActivityLoading(false);
        }
      }
    }

    loadActivity();

    return () => {
      cancelled = true;
    };
  }, []);

  const stats = [
    {
      label: "Revenue",
      value: statsLoading
        ? "..."
        : `$${dashboardStats.revenueGenerated.toLocaleString()}`,
      change: "Live",
      description:
        "generated by AI workforce",
      icon: TrendingUp,
    },
    {
      label: "AI Employees",
      value: statsLoading
        ? "..."
        : String(
            dashboardStats.aiEmployees.total
          ),
      change: statsLoading
        ? "..."
        : `${dashboardStats.aiEmployees.running} running`,
      description:
        "total digital workforce",
      icon: Bot,
    },
    {
      label: "Tasks Completed",
      value: statsLoading
        ? "..."
        : dashboardStats.tasksCompleted.toLocaleString(),
      change: "Live",
      description:
        "completed by AI employees",
      icon: CheckCircle2,
    },
    {
      label: "Automations",
      value: statsLoading
        ? "..."
        : String(
            dashboardStats.automations.total
          ),
      change: statsLoading
        ? "..."
        : `${dashboardStats.automations.running} running`,
      description: statsLoading
        ? "loading workflow data"
        : `${dashboardStats.automations.runs} total runs`,
      icon: Workflow,
    },
  ];

  return (
    <div className="min-h-full bg-[#09090B] text-white">
      <div className="mx-auto max-w-[1500px] px-6 py-8 lg:px-8">
        {/* HEADER */}
        <div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end">
          <div>
            <div className="mb-2 flex items-center gap-2 text-sm text-zinc-500">
              <span>Overview</span>

              <ChevronRight size={14} />

              <span className="text-zinc-300">
                Dashboard
              </span>
            </div>

            <h1 className="text-3xl font-semibold tracking-tight">
              Welcome back, {userName}
            </h1>

            <p className="mt-2 text-sm text-zinc-500">
              Build, automate and manage your
              business with J10 AI.
            </p>
          </div>

          <div className="relative">
            <button
              type="button"
              onClick={() =>
                setCreateOpen((current) => !current)
              }
              aria-expanded={createOpen}
              className="
                group flex items-center gap-2 rounded-xl
                border border-white/10 bg-white/[0.04]
                px-4 py-2.5 text-sm font-medium
                transition-all hover:border-blue-500/30
                hover:bg-blue-500/10
              "
            >
              <Plus size={17} />
              Create
              <ChevronRight
                size={15}
                className={`transition-transform ${
                  createOpen ? "rotate-90" : ""
                }`}
              />
            </button>

            {createOpen && (
              <div className="absolute right-0 top-[calc(100%+8px)] z-20 w-64 rounded-2xl border border-white/[0.09] bg-[#101115] p-2 shadow-2xl shadow-black/50">
                {[
                  {
                    label: "Create AI employee",
                    href: "/dashboard/ai-employees",
                    icon: Bot,
                  },
                  {
                    label: "Build workflow",
                    href: "/dashboard/automation/flow",
                    icon: Workflow,
                  },
                  {
                    label: "Add CRM contact",
                    href: "/dashboard/crm",
                    icon: Plus,
                  },
                  {
                    label: "Configure WhatsApp",
                    href: "/dashboard/whatsapp",
                    icon: MessageSquare,
                  },
                ].map((action) => {
                  const Icon = action.icon;

                  return (
                    <Link
                      key={action.href}
                      href={action.href}
                      onClick={() => setCreateOpen(false)}
                      className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-white/60 transition hover:bg-white/[0.055] hover:text-white"
                    >
                      <Icon
                        size={16}
                        className="text-blue-400"
                      />
                      {action.label}
                    </Link>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* J10 AI COMMAND CENTER */}
        <div
          id="j10-ai"
          className="mb-6 scroll-mt-24"
        >
          <AIWidget />
        </div>

        {/* BUSINESS OVERVIEW */}
        <div className="mb-4">
          <h2 className="text-lg font-semibold">
            Business Overview
          </h2>

          <p className="mt-1 text-sm text-zinc-600">
            Your business performance and
            operations at a glance.
          </p>
        </div>

        {/* STATS */}
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {stats.map((stat) => {
            const Icon = stat.icon;

            return (
              <div
                key={stat.label}
                className="
                  group relative overflow-hidden
                  rounded-2xl
                  border border-white/[0.07]
                  bg-[#111216]
                  p-5
                  transition-all duration-300
                  hover:-translate-y-1
                  hover:border-blue-500/20
                  hover:bg-[#14161b]
                "
              >
                <div className="absolute -right-10 -top-10 h-24 w-24 rounded-full bg-blue-600/10 blur-3xl transition-opacity group-hover:opacity-100" />

                <div className="relative">
                  <div className="mb-5 flex items-center justify-between">
                    <div className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/[0.07] bg-white/[0.04]">
                      <Icon
                        size={18}
                        className="text-blue-400"
                      />
                    </div>

                    <MoreHorizontal
                      size={18}
                      className="text-zinc-600"
                    />
                  </div>

                  <p className="text-sm text-zinc-500">
                    {stat.label}
                  </p>

                  <div className="mt-1 flex items-end gap-3">
                    <span className="text-2xl font-semibold tracking-tight">
                      {stat.value}
                    </span>

                    <span className="mb-1 rounded-md bg-emerald-500/10 px-2 py-0.5 text-xs font-medium text-emerald-400">
                      {stat.change}
                    </span>
                  </div>

                  <p className="mt-2 text-xs text-zinc-600">
                    {stat.description}
                  </p>
                </div>
              </div>
            );
          })}
        </div>

        {/* EMPLOYEE STATUS */}
        <div className="mt-4 grid gap-3 sm:grid-cols-3">
          <EmployeeStatusCard
            label="Running"
            value={
              dashboardStats.aiEmployees.running
            }
            loading={statsLoading}
            status="running"
          />

          <EmployeeStatusCard
            label="Paused"
            value={
              dashboardStats.aiEmployees.paused
            }
            loading={statsLoading}
            status="paused"
          />

          <EmployeeStatusCard
            label="Offline"
            value={
              dashboardStats.aiEmployees.offline
            }
            loading={statsLoading}
            status="offline"
          />
        </div>

        {/* REAL RECENT ACTIVITY */}
        <section className="mt-6 rounded-2xl border border-white/[0.07] bg-[#111216] p-6">
          <div className="mb-5 flex items-center justify-between">
            <div>
              <h2 className="font-semibold">
                Recent Activity
              </h2>

              <p className="mt-1 text-xs text-zinc-600">
                Real activity across your J10 NEXUS workspace
              </p>
            </div>

            <div className="flex items-center gap-3">
              <div className="flex items-center gap-2 rounded-full border border-emerald-500/10 bg-emerald-500/[0.05] px-2.5 py-1 text-[10px] text-emerald-400">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
                Live
              </div>
              <Link
                href="/dashboard/activity"
                className="text-xs font-medium text-blue-400 transition hover:text-blue-300"
              >
                View all
              </Link>
            </div>
          </div>

          {activityLoading ? (
            <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">
              {[1, 2, 3].map((item) => (
                <div
                  key={item}
                  className="h-[76px] animate-pulse rounded-xl border border-white/[0.04] bg-white/[0.015]"
                />
              ))}
            </div>
          ) : activity.length === 0 ? (
            <div className="rounded-xl border border-dashed border-white/[0.07] bg-white/[0.015] px-6 py-10 text-center">
              <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-xl bg-white/[0.04]">
                <Zap
                  size={17}
                  className="text-zinc-600"
                />
              </div>

              <p className="mt-4 text-sm font-medium text-zinc-400">
                No activity yet
              </p>

              <p className="mt-1 text-xs text-zinc-600">
                Actions performed in J10 NEXUS
                will appear here.
              </p>
            </div>
          ) : (
            <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">
              {activity.map((item) => {
                const Icon =
                  getActivityIcon(item.action);

                return (
                  <Link
                    key={item.id}
                    href="/dashboard/activity"
                    className="
                      group
                      flex items-center gap-3
                      rounded-xl
                      border border-white/[0.04]
                      bg-white/[0.015]
                      p-3
                      transition-all
                      hover:border-blue-500/15
                      hover:bg-white/[0.03]
                    "
                  >
                    <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-white/[0.06] bg-white/[0.03]">
                      <Icon
                        size={15}
                        className={getActivityColor(
                          item.action
                        )}
                      />
                    </div>

                    <div className="min-w-0 flex-1">
                      <p className="truncate text-sm text-zinc-300">
                        {item.title}
                      </p>

                      <p className="mt-1 truncate text-xs text-zinc-600">
                        {formatActivityTime(
                          item.created_at
                        )}
                      </p>
                    </div>

                    <ChevronRight
                      size={15}
                      className="text-zinc-700 transition-all group-hover:translate-x-0.5 group-hover:text-blue-400"
                    />
                  </Link>
                );
              })}
            </div>
          )}
        </section>

        {/* QUICK ACTIONS */}
        <section className="mt-6">
          <div className="mb-4">
            <h2 className="text-lg font-semibold">
              Quick Actions
            </h2>

            <p className="mt-1 text-sm text-zinc-600">
              Create, automate and manage your
              business from one place.
            </p>
          </div>

          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {quickActions.map((action) => {
              const Icon = action.icon;

              const content = (
                <>
                  <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-white/[0.07] bg-gradient-to-br from-white/[0.07] to-white/[0.02] transition-all group-hover:border-blue-500/20 group-hover:bg-blue-500/10">
                    <Icon
                      size={18}
                      className={
                        action.status === "ready"
                          ? "text-zinc-400 transition-colors group-hover:text-blue-400"
                          : "text-zinc-600"
                      }
                    />
                  </div>

                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-medium text-zinc-200">
                      {action.title}
                    </p>

                    <p className="mt-1 truncate text-xs text-zinc-600">
                      {action.description}
                    </p>
                  </div>

                  {action.status === "ready" ? (
                    <ArrowUpRight
                      size={16}
                      className="text-zinc-700 transition-all group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-blue-400"
                    />
                  ) : (
                    <span className="rounded-full border border-amber-400/15 bg-amber-400/[0.06] px-2 py-1 text-[8px] font-bold uppercase tracking-wider text-amber-300/60">
                      Building
                    </span>
                  )}
                </>
              );

              const className = `
                group flex items-center gap-4 rounded-2xl
                border border-white/[0.07] bg-[#111216]
                p-4 text-left transition-all duration-300
                ${
                  action.status === "ready"
                    ? "hover:-translate-y-0.5 hover:border-blue-500/20 hover:bg-[#14161b]"
                    : "cursor-not-allowed opacity-65"
                }
              `;

              if (
                action.status === "ready" &&
                action.href
              ) {
                return (
                  <Link
                    key={action.title}
                    href={action.href}
                    className={className}
                  >
                    {content}
                  </Link>
                );
              }

              return (
                <button
                  key={action.title}
                  type="button"
                  disabled
                  className={className}
                >
                  {content}
                </button>
              );
            })}
          </div>
        </section>

        {/* BOTTOM STATUS */}
        <div className="mt-6 grid gap-4 md:grid-cols-3">
          {/* SYSTEM STATUS */}
          <div className="rounded-2xl border border-white/[0.07] bg-[#111216] p-5">
            <div className="flex items-center gap-3">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-500/10">
                <Zap
                  size={16}
                  className="text-emerald-400"
                />
              </div>

              <div>
                <p className="text-sm font-medium">
                  System Status
                </p>

                <p className="text-xs text-emerald-400">
                  All systems operational
                </p>
              </div>
            </div>
          </div>

          {/* AI OPERATIONS */}
          <div className="rounded-2xl border border-white/[0.07] bg-[#111216] p-5">
            <div className="flex items-center gap-3">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-blue-500/10">
                <Bot
                  size={16}
                  className="text-blue-400"
                />
              </div>

              <div>
                <p className="text-sm font-medium">
                  AI Operations
                </p>

                <p className="text-xs text-zinc-500">
                  {statsLoading
                    ? "Loading workforce..."
                    : `${dashboardStats.aiEmployees.running} ${
                        dashboardStats
                          .aiEmployees.running ===
                        1
                          ? "employee"
                          : "employees"
                      } working`}
                </p>
              </div>
            </div>
          </div>

          {/* AUTOMATIONS */}
          <div className="rounded-2xl border border-white/[0.07] bg-[#111216] p-5">
            <div className="flex items-center gap-3">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-violet-500/10">
                <Workflow
                  size={16}
                  className="text-violet-400"
                />
              </div>

              <div>
                <p className="text-sm font-medium">
                  Automations
                </p>

                <p className="text-xs text-zinc-500">
                  {statsLoading
                    ? "Loading workflows..."
                    : `${dashboardStats.automations.running} running · ${dashboardStats.automations.draft} draft · ${dashboardStats.automations.runs} runs`}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function EmployeeStatusCard({
  label,
  value,
  loading,
  status,
}: {
  label: string;
  value: number;
  loading: boolean;
  status:
    | "running"
    | "paused"
    | "offline";
}) {
  const dotStyles = {
    running: "bg-emerald-400",
    paused: "bg-amber-400",
    offline: "bg-zinc-600",
  };

  return (
    <div className="rounded-xl border border-white/[0.06] bg-[#111216] px-4 py-3">
      <div className="flex items-center justify-between">
        <p className="text-xs text-zinc-500">
          {label}
        </p>

        <span
          className={`h-2 w-2 rounded-full ${
            dotStyles[status]
          }`}
        />
      </div>

      <p className="mt-2 text-lg font-semibold">
        {loading ? "..." : value}
      </p>
    </div>
  );
}

function getActivityIcon(
  action: string
) {
  switch (action) {
    case "ai_employee_created":
      return Bot;

    case "ai_employee_paused":
      return Pause;

    case "ai_employee_resumed":
      return Play;

    case "ai_employee_edited":
      return Pencil;

    case "ai_employee_deleted":
      return Trash2;

    case "workflow_created":
    case "workflow_started":
    case "workflow_paused":
    case "workflow_resumed":
    case "workflow_ran":
    case "workflow_edited":
    case "workflow_deleted":
      return Workflow;

    case "whatsapp_created":
      return MessageSquare;

    default:
      return Zap;
  }
}

function getActivityColor(
  action: string
) {
  switch (action) {
    case "ai_employee_created":
      return "text-blue-400";

    case "ai_employee_paused":
      return "text-amber-400";

    case "ai_employee_resumed":
      return "text-emerald-400";

    case "ai_employee_edited":
      return "text-violet-400";

    case "ai_employee_deleted":
      return "text-red-400";

    case "workflow_created":
      return "text-blue-400";

    case "workflow_started":
    case "workflow_resumed":
    case "workflow_ran":
      return "text-emerald-400";

    case "workflow_paused":
      return "text-amber-400";

    case "workflow_edited":
      return "text-violet-400";

    case "workflow_deleted":
      return "text-red-400";

    default:
      return "text-zinc-400";
  }
}

function formatActivityTime(
  createdAt: string
) {
  const created =
    new Date(createdAt).getTime();

  const now = Date.now();

  const difference =
    Math.max(0, now - created);

  const seconds = Math.floor(
    difference / 1000
  );

  if (seconds < 60) {
    return "Just now";
  }

  const minutes = Math.floor(
    seconds / 60
  );

  if (minutes < 60) {
    return `${minutes} ${
      minutes === 1
        ? "minute"
        : "minutes"
    } ago`;
  }

  const hours = Math.floor(
    minutes / 60
  );

  if (hours < 24) {
    return `${hours} ${
      hours === 1
        ? "hour"
        : "hours"
    } ago`;
  }

  const days = Math.floor(
    hours / 24
  );

  if (days < 7) {
    return `${days} ${
      days === 1
        ? "day"
        : "days"
    } ago`;
  }

  return new Date(
    createdAt
  ).toLocaleDateString();
}
