"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, BookOpen, Check, ChevronRight, Search } from "lucide-react";
import { PUBLIC_PLANS } from "@/lib/billing/plans";
import { INTEGRATION_CATEGORIES, J10_INTEGRATIONS } from "@/lib/integrations/catalog";

const nav = [
  ["Start here", [["Overview", "overview"], ["Quickstart", "quickstart"], ["How J10 works", "architecture"]]],
  ["Products", [["Command Center", "command-center"], ["Inbox & Receptionist", "inbox"], ["Leads, Booking & Pay", "revenue"], ["Campaigns & Reviews", "growth"], ["Knowledge & Automations", "knowledge"]]],
  ["Operate", [["Connections", "connections"], ["Team & permissions", "team"], ["Plans & billing", "billing"], ["Security", "security"], ["Troubleshooting", "troubleshooting"]]],
] as const;

const searchable = nav.flatMap(([group, items]) => items.map(([title, id]) => ({ group, title, id })));

export default function DocsClient() {
  const [query, setQuery] = useState("");
  const results = useMemo(() => query.trim() ? searchable.filter(x => `${x.group} ${x.title}`.toLowerCase().includes(query.toLowerCase())) : [], [query]);
  return <>
    <section className="relative overflow-hidden border-b border-[#d9b85f]/12 px-5 py-16 sm:py-20">
      <div className="pointer-events-none absolute left-1/2 top-0 h-80 w-[760px] -translate-x-1/2 bg-[radial-gradient(ellipse,rgba(105,43,195,.3),transparent_68%)]" />
      <div className="relative mx-auto max-w-4xl text-center">
        <div className="inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.22em] text-[#efc76b]"><BookOpen size={15}/>J10 Documentation</div>
        <h1 className="mt-5 text-4xl font-extrabold tracking-[-.045em] sm:text-6xl">Build your business <span className="text-[#b77cff]">operator.</span></h1>
        <p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-white/60">Clear setup instructions for connecting channels, teaching J10 about your business, launching AI assistance, and managing the work that creates revenue.</p>
        <div className="relative mx-auto mt-8 max-w-2xl text-left"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#efc76b]" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search J10 documentation" aria-label="Search documentation" className="w-full rounded-2xl border border-[#d9b85f]/25 bg-[#0d0914]/95 py-4 pl-12 pr-4 text-sm text-white outline-none placeholder:text-white/32 focus:border-[#efc76b]/60"/>{results.length>0&&<div className="absolute inset-x-0 top-[calc(100%+8px)] z-20 rounded-2xl border border-[#d9b85f]/20 bg-[#0c0912] p-2 shadow-2xl">{results.map(x=><a key={x.id} href={`#${x.id}`} onClick={()=>setQuery("")} className="flex items-center justify-between rounded-xl px-4 py-3 text-sm hover:bg-white/5"><span><small className="mr-2 text-[#efc76b]">{x.group}</small>{x.title}</span><ChevronRight size={15}/></a>)}</div>}</div>
      </div>
    </section>
    <div className="mx-auto grid max-w-[1360px] gap-10 px-5 py-12 lg:grid-cols-[230px_minmax(0,760px)_190px] lg:px-8">
      <aside className="hidden lg:block"><nav className="sticky top-6 space-y-7">{nav.map(([group,items])=><div key={group}><p className="mb-3 text-[10px] font-extrabold uppercase tracking-[.2em] text-[#efc76b]">{group}</p><div className="grid gap-1">{items.map(([title,id])=><a key={id} href={`#${id}`} className="rounded-lg px-3 py-2 text-sm text-white/48 transition hover:bg-white/5 hover:text-white">{title}</a>)}</div></div>)}</nav></aside>
      <article className="min-w-0 space-y-20 text-[15px] leading-7 text-white/65">
        <Doc id="overview" eyebrow="Start here" title="What J10 NEXUS does"><p>J10 NEXUS is an AI revenue and operations system for service businesses. It brings customer conversations, leads, appointments, payment activity, follow-up, reviews, and business knowledge into one workspace.</p><Callout title="The operating idea">A customer contacts your business. J10 answers from approved knowledge, captures the opportunity, helps qualify it, moves it toward a booking or payment, and keeps the full activity visible to your team.</Callout></Doc>
        <Doc id="quickstart" eyebrow="Quickstart" title="Launch in six steps"><Steps items={["Create your workspace and confirm the business name, timezone, and contact details.","Add services, prices, hours, policies, and FAQs to Knowledge.","Open Connections and connect only the customer channels you actively use.","Configure the AI Receptionist tone, goals, handoff rules, and booking behavior.","Test common customer questions and correct any missing knowledge before launch.","Turn the workflow on, watch the Inbox, and use Command Center to review outcomes."]}/><Callout title="Launch rule">Do not automate an answer J10 has not been taught. A short, accurate knowledge base is better than a large unreviewed one.</Callout></Doc>
        <Doc id="architecture" eyebrow="Architecture" title="One workspace, connected products"><p>Every J10 product has one job, while sharing the same workspace context. Command Center summarizes the work. Inbox holds conversations. Lead Center tracks opportunities. Booking, Pay, Reviews, and Campaigns move the customer journey forward. Knowledge grounds the AI. Automations connect approved triggers to actions.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{["Customer channels → Inbox","Knowledge → AI assistance","Lead → Booking → Pay"].map(x=><div key={x} className="rounded-xl border border-[#d9b85f]/14 bg-white/[.025] p-4 text-sm font-bold text-white">{x}</div>)}</div></Doc>
        <Doc id="command-center" eyebrow="Products" title="Command Center"><p>Use Command Center as the daily business view. It shows recent activity, the opportunities that need attention, booking and payment signals, and AI performance without requiring you to open every product.</p><Bullets items={["Review the day before opening individual tools.","Follow urgent exceptions and human handoffs first.","Use Ask J10 to summarize activity and identify work that needs attention."]}/></Doc>
        <Doc id="inbox" eyebrow="Products" title="Inbox and AI Receptionist"><p>Inbox keeps supported customer conversations together. The AI Receptionist handles approved FAQs, captures intent, and follows your handoff rules. A person can take over whenever judgment or sensitive information is required.</p><Bullets items={["Use filters to separate unread, assigned, and automated conversations.","Keep answers grounded in Knowledge—never in invented business details.","Set a clear human handoff for complaints, exceptions, or high-value requests."]}/></Doc>
        <Doc id="revenue" eyebrow="Products" title="Lead Center, Booking, and J10 Pay"><p>Lead Center is the pipeline for captured opportunities. Booking converts qualified intent into an appointment. J10 Pay tracks supported payment links, deposits, and transaction status. They remain separate products so each screen stays focused.</p><Bullets items={["Move leads through simple, meaningful stages.","Connect a calendar before offering live availability.","Use deposits when the business requires commitment before a booking is confirmed."]}/></Doc>
        <Doc id="growth" eyebrow="Products" title="Campaigns and Reviews"><p>Campaigns helps re-engage opted-in leads and customers with focused messages. Reviews helps request feedback after a completed customer outcome and gives the team one place to follow up.</p><Callout title="Permission matters">Only contact people through channels and message types your business is authorized to use. Provider rules and customer consent still apply.</Callout></Doc>
        <Doc id="knowledge" eyebrow="Products" title="Knowledge and Automations"><p>Knowledge is the approved source for services, pricing, policies, business hours, and FAQs. Automations turn clear events into repeatable actions, such as sending a reminder after a booking or assigning a new lead.</p><Steps items={["Choose a template close to the outcome you want.","Confirm the trigger and its required connection.","Review every action, delay, and message.","Test with one record before publishing.","Monitor the first live runs and pause if the outcome is wrong."]}/></Doc>
        <Doc id="connections" eyebrow="Operate" title="Connections"><p>Connections is the single place to manage J10&apos;s external services. The catalog covers {J10_INTEGRATIONS.length} business tools across customer channels, scheduling, payments, CRM, commerce, accounting, marketing, files, team operations, automation, and field services.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{INTEGRATION_CATEGORIES.map(category=>{const count=J10_INTEGRATIONS.filter(x=>x.category===category).length;return <div key={category} className="flex items-center justify-between rounded-xl border border-[#d9b85f]/14 bg-white/[.025] p-4 text-sm text-white/75"><span><Check className="mr-2 inline text-[#efc76b]" size={15}/>{category}</span><small className="text-white/35">{count} {count===1?"app":"apps"}</small></div>})}</div><Callout title="Connection status">Available means working in J10 today. Next marks the launch integration queue. Roadmap items are planned and prioritized by customer demand and provider access.</Callout><Link href="/integrations" className="inline-flex items-center gap-2 font-bold text-[#efc76b]">Explore all {J10_INTEGRATIONS.length} integrations <ArrowRight size={16}/></Link></Doc>
        <Doc id="team" eyebrow="Operate" title="Team and permissions"><p>Invite only the people who need workspace access. Owners control billing and workspace-level settings. Admins configure operations. Managers and agents handle daily work. Viewers have read-only access where enabled.</p></Doc>
        <Doc id="billing" eyebrow="Operate" title="Plans and billing"><p>These are the current public J10 plans. This table is generated from the same plan source used by the pricing page.</p><div className="mt-6 overflow-hidden rounded-2xl border border-[#d9b85f]/15"><table className="w-full text-left text-sm"><thead className="bg-white/[.04] text-[#efc76b]"><tr><th className="p-4">Plan</th><th className="p-4">Monthly</th><th className="hidden p-4 sm:table-cell">Messages</th></tr></thead><tbody>{PUBLIC_PLANS.map(p=><tr key={p.id} className="border-t border-[#d9b85f]/10"><td className="p-4 font-bold text-white">{p.name}</td><td className="p-4">{p.quoteOnly?`From $${p.price}`:`$${p.price}`}</td><td className="hidden p-4 sm:table-cell">{p.messageLimit.toLocaleString()}+</td></tr>)}</tbody></table></div><p className="mt-4 text-xs text-white/40">Provider usage charges may be separate. Enterprise requires a custom agreement.</p></Doc>
        <Doc id="security" eyebrow="Operate" title="Security and data control"><p>J10 uses workspace-scoped access controls, protected server-side credentials, verified provider events, and role-based permissions. Your team remains responsible for deciding what should be automated and when a person must take over.</p><Link href="/security" className="mt-5 inline-flex items-center gap-2 font-bold text-[#efc76b]">Read the security overview <ArrowRight size={16}/></Link></Doc>
        <Doc id="troubleshooting" eyebrow="Help" title="Troubleshooting"><div className="space-y-5">{[["A connection stopped working","Open Connections, check its status, and reconnect or reauthorize the provider. Then send a controlled test."],["J10 gave an incomplete answer","Add or correct the missing business information in Knowledge, then test the same question again."],["A lead did not move","Open the lead activity and automation run. Confirm the trigger, required fields, connection, and next action."],["A booking time is wrong","Verify workspace timezone, connected calendar timezone, availability, and service duration."],["You still need help","Email contact@j10-nexus.com with the workspace name, affected product, time of the issue, and what you expected."]].map(([q,a])=><div key={q} className="border-b border-[#d9b85f]/10 pb-5"><h3 className="font-bold text-white">{q}</h3><p className="mt-1">{a}</p></div>)}</div></Doc>
      </article>
      <aside className="hidden xl:block"><div className="sticky top-6 rounded-2xl border border-[#d9b85f]/15 bg-white/[.025] p-5"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#efc76b]">Need help?</p><p className="mt-3 text-sm leading-6 text-white/50">Tell the team which workspace and product you are using.</p><Link href="/contact" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-white">Contact J10 <ArrowRight size={15}/></Link></div></aside>
    </div>
  </>;
}

function Doc({id,eyebrow,title,children}:{id:string;eyebrow:string;title:string;children:React.ReactNode}) { return <section id={id} className="scroll-mt-8"><p className="text-[11px] font-extrabold uppercase tracking-[.2em] text-[#efc76b]">{eyebrow}</p><h2 className="mt-2 text-3xl font-extrabold tracking-[-.035em] text-white sm:text-4xl">{title}</h2><div className="mt-5 space-y-5">{children}</div></section>; }
function Callout({title,children}:{title:string;children:React.ReactNode}) { return <div className="rounded-2xl border border-[#d9b85f]/20 bg-[linear-gradient(135deg,rgba(217,184,95,.07),rgba(106,46,189,.08))] p-5"><p className="font-bold text-white">{title}</p><p className="mt-1 text-sm">{children}</p></div>; }
function Bullets({items}:{items:string[]}) { return <ul className="space-y-3">{items.map(x=><li key={x} className="flex gap-3"><Check size={17} className="mt-1 shrink-0 text-[#efc76b]"/><span>{x}</span></li>)}</ul>; }
function Steps({items}:{items:string[]}) { return <ol className="space-y-3">{items.map((x,i)=><li key={x} className="flex gap-4 rounded-xl border border-[#d9b85f]/10 bg-white/[.02] p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-[#6b2dbd] text-xs font-bold text-white">{i+1}</span><span>{x}</span></li>)}</ol>; }
