import type { ServicePlaybook } from "../types";

export const beautyGroomingPlaybook: ServicePlaybook = {
  playbookKey: "beauty_grooming",
  industryName: "Beauty & Grooming",
  displayName: "Beauty & Grooming Playbook",
  description: "Playbook for hair salons, barbershops, nail studios, lash technicians, and estheticians.",
  terminology: {
    serviceLabel: "service",
    bookingLabel: "appointment",
    providerLabel: "stylist",
  },
  defaultDurationMinutes: 60,
  services: [
    {
      key: "balayage",
      name: "Balayage",
      price: 180,
      priceDisplay: "$180",
      durationMinutes: 180,
      description: "Custom hand-painted highlighting technique for natural, blended dimension.",
      requiresQuote: false,
    },
    {
      key: "silk_press",
      name: "Silk Press",
      price: 85,
      priceDisplay: "$85",
      durationMinutes: 90,
      description: "Non-chemical thermal smoothing treatment providing body and shine.",
      requiresQuote: false,
    },
    {
      key: "gel_manicure",
      name: "Gel Manicure",
      price: 45,
      priceDisplay: "$45",
      durationMinutes: 45,
      description: "Long-lasting gel polish cured under LED light with cuticle care.",
      requiresQuote: false,
    },
    {
      key: "haircut",
      name: "Haircut",
      price: 55,
      priceDisplay: "$55",
      durationMinutes: 45,
      description: "Precision cut tailored to hair texture, shape, and lifestyle.",
      requiresQuote: false,
    },
    {
      key: "fade",
      name: "Fade",
      price: 40,
      priceDisplay: "$40",
      durationMinutes: 40,
      description: "Crisp taper or skin fade with lineup and styling.",
      requiresQuote: false,
    },
    {
      key: "lash_extension",
      name: "Lash Extension",
      price: 130,
      priceDisplay: "$130",
      durationMinutes: 120,
      description: "Full set of classic or volume semi-permanent eyelash extensions.",
      requiresQuote: false,
    },
    {
      key: "custom_color_correction",
      name: "Color Correction",
      price: null,
      priceDisplay: "Custom Quote",
      durationMinutes: 240,
      description: "Complex corrective color process requiring consultation.",
      requiresQuote: true,
    },
  ],
  qualificationQuestions: {
    service: "Which service or treatment are you looking to book?",
    date: "What day works best for you?",
    time: "Do you prefer mornings, afternoons, or a specific time?",
  },
  escalationKeywords: [
    "complaint",
    "refund",
    "manager",
    "allergic",
    "reaction",
    "dissatisfied",
    "ruined",
    "burn",
  ],
  systemPromptInstructions:
    "You are an AI booking concierge for a premier beauty salon and grooming studio. Assist clients with appointment availability, treatment questions, and scheduling.",
};
