-- CI CERTIFICATION ONLY. This recreates the pre-repository legacy foundation
-- that Day 14 assumed already existed. It is never copied to supabase/migrations
-- in git and must never be deployed to production.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE public.workspaces (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL DEFAULT 'Legacy workspace', slug text NOT NULL UNIQUE DEFAULT gen_random_uuid()::text, brand_name text NOT NULL DEFAULT 'Legacy', owner_user_id uuid REFERENCES auth.users(id), plan text NOT NULL DEFAULT 'growth', status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.workspace_memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, role text NOT NULL DEFAULT 'viewer', status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id,user_id));
CREATE TABLE public.contacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid REFERENCES public.workspaces(id) ON DELETE CASCADE, name text NOT NULL DEFAULT 'Legacy contact', email text, phone text, source text NOT NULL DEFAULT 'direct', deal_stage text NOT NULL DEFAULT 'lead', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.inbox_threads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid REFERENCES public.workspaces(id) ON DELETE CASCADE, contact_id uuid REFERENCES public.contacts(id) ON DELETE SET NULL, channel text NOT NULL DEFAULT 'website', status text NOT NULL DEFAULT 'active', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.inbox_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid REFERENCES public.workspaces(id) ON DELETE CASCADE, thread_id uuid REFERENCES public.inbox_threads(id) ON DELETE CASCADE, direction text NOT NULL DEFAULT 'inbound', provider text NOT NULL DEFAULT 'internal', content text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.employees (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES auth.users(id), name text NOT NULL DEFAULT 'Legacy employee', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.ai_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES auth.users(id), title text NOT NULL DEFAULT 'Legacy task', status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.automations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, name text NOT NULL DEFAULT 'Legacy automation', trigger_type text NOT NULL DEFAULT 'manual', trigger_config jsonb NOT NULL DEFAULT '{}'::jsonb, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT automations_trigger_type_check CHECK(trigger_type IN ('manual','new_crm_contact','crm_status_changed','new_ai_task','ai_task_completed','schedule')));
CREATE TABLE public.automation_steps (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), automation_id uuid NOT NULL REFERENCES public.automations(id) ON DELETE CASCADE, step_order integer NOT NULL DEFAULT 1, step_type text NOT NULL DEFAULT 'action', config jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.automation_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), automation_id uuid NOT NULL REFERENCES public.automations(id) ON DELETE CASCADE, user_id uuid REFERENCES auth.users(id), status text NOT NULL DEFAULT 'queued', trigger_payload jsonb NOT NULL DEFAULT '{}'::jsonb, started_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.automation_run_steps (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), run_id uuid NOT NULL REFERENCES public.automation_runs(id) ON DELETE CASCADE, automation_id uuid REFERENCES public.automations(id) ON DELETE CASCADE, step_order integer NOT NULL DEFAULT 1, status text NOT NULL DEFAULT 'queued', created_at timestamptz NOT NULL DEFAULT now());
CREATE OR REPLACE FUNCTION public.is_workspace_member(target_workspace_id uuid) RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT EXISTS (SELECT 1 FROM public.workspace_memberships WHERE workspace_id = target_workspace_id AND user_id = auth.uid() AND status = 'active') $$;
CREATE OR REPLACE FUNCTION public.has_workspace_role(target_workspace_id uuid, accepted_roles text[]) RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT EXISTS (SELECT 1 FROM public.workspace_memberships WHERE workspace_id = target_workspace_id AND user_id = auth.uid() AND status = 'active' AND role = ANY(accepted_roles)) $$;
