-- CI CERTIFICATION ONLY. Current-production-shaped foundation for Stage 1.
-- This file is never a production migration and contains neither data nor credentials.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE public.workspaces (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL DEFAULT 'Certification workspace', slug text NOT NULL UNIQUE DEFAULT gen_random_uuid()::text, brand_name text NOT NULL DEFAULT 'Certification', owner_user_id uuid REFERENCES auth.users(id), plan text NOT NULL DEFAULT 'growth', status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.workspace_memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, role text NOT NULL DEFAULT 'viewer', status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id,user_id));
CREATE TABLE public.contacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE, name text NOT NULL, first_name text, email text, phone text, source text NOT NULL DEFAULT 'direct', deal_stage text NOT NULL DEFAULT 'lead', type text, status text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id,id));
CREATE TABLE public.inbox_threads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE, contact_id uuid, channel text NOT NULL CHECK(channel IN ('whatsapp','website','crm')), external_thread_id text, status text NOT NULL DEFAULT 'active', priority text NOT NULL DEFAULT 'medium', unread_count integer NOT NULL DEFAULT 0, last_message_at timestamptz NOT NULL DEFAULT now(), metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id,id), FOREIGN KEY(workspace_id,contact_id) REFERENCES public.contacts(workspace_id,id) ON DELETE SET NULL(contact_id));
CREATE TABLE public.inbox_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE, thread_id uuid NOT NULL, direction text NOT NULL CHECK(direction IN ('inbound','outbound')), provider text NOT NULL DEFAULT 'internal', external_message_id text, content text NOT NULL, delivery_status text NOT NULL DEFAULT 'sent', message_type text NOT NULL DEFAULT 'text', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id,id), UNIQUE(workspace_id,external_message_id), FOREIGN KEY(workspace_id,thread_id) REFERENCES public.inbox_threads(workspace_id,id) ON DELETE CASCADE);
CREATE TABLE public.website_funnels (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, slug text NOT NULL, title text NOT NULL DEFAULT 'Certification funnel', primary_cta_link text, is_published boolean NOT NULL DEFAULT false, UNIQUE(workspace_id,slug));
CREATE TABLE public.automations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, name text NOT NULL, trigger_type text NOT NULL DEFAULT 'manual', trigger_config jsonb NOT NULL DEFAULT '{}'::jsonb, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT automations_trigger_type_check CHECK(trigger_type IN ('manual','new_crm_contact','crm_status_changed','new_ai_task','ai_task_completed','schedule','integration_event')));
CREATE TABLE public.automation_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE, automation_id uuid NOT NULL REFERENCES public.automations(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES auth.users(id), status text NOT NULL DEFAULT 'queued', trigger_payload jsonb NOT NULL DEFAULT '{}'::jsonb, started_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now());
CREATE OR REPLACE FUNCTION public.is_workspace_member(target_workspace_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, auth, pg_temp AS $$ SELECT EXISTS (SELECT 1 FROM public.workspace_memberships WHERE workspace_id=target_workspace_id AND user_id=auth.uid() AND status='active') $$;
CREATE OR REPLACE FUNCTION public.has_workspace_role(target_workspace_id uuid, accepted_roles text[]) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, auth, pg_temp AS $$ SELECT EXISTS (SELECT 1 FROM public.workspace_memberships WHERE workspace_id=target_workspace_id AND user_id=auth.uid() AND status='active' AND role=ANY(accepted_roles)) $$;
