"use client";
import {Menu,X} from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import {useState} from "react";
const links=[["Product","/#product"],["Services","/#services"],["Integrations","/integrations"],["Pricing","/pricing"],["Docs","/docs"],["Security","/security"],["Contact","/contact"]] as const;
export default function Navbar(){
 const [open,setOpen]=useState(false);
 return <header className="relative z-50 border-b border-[#d9b85f]/15 bg-[#04030a]/95 text-white backdrop-blur-xl"><nav className="mx-auto flex h-[72px] max-w-[1600px] items-center justify-between px-4 sm:px-8" aria-label="Main navigation"><Link href="/" className="flex items-center gap-2"><Image src="/brand/j10-logo.png" alt="" width={40} height={40} priority className="h-8 w-8 object-contain brightness-0 invert sm:h-10 sm:w-10"/><span className="text-[17px] font-semibold tracking-[.05em] sm:text-[22px]">J10 NEXUS</span></Link><div className="hidden items-center gap-6 text-[13px] lg:flex">{links.map(([label,href])=><Link key={label} href={href} className="transition hover:text-[#efc76b]">{label}</Link>)}</div><div className="flex items-center gap-2 sm:gap-3"><Link href="/login" className="hidden rounded-xl border border-[#d9b85f]/30 px-5 py-2.5 text-[15px] transition hover:border-[#efc76b] md:block">Sign in</Link><Link href="/login?intent=signup&plan=growth&trial=1" className="rounded-xl bg-[linear-gradient(115deg,#4b159f,#7c3aed)] px-3 py-2.5 text-[13px] font-semibold shadow-[0_8px_30px_rgba(124,58,237,.25)] sm:px-6 sm:text-[15px]">Start Free</Link><button onClick={()=>setOpen(v=>!v)} aria-label="Toggle menu" aria-expanded={open} aria-controls="mobile-menu" className="rounded-lg border border-[#d9b85f]/20 p-2 lg:hidden">{open?<X/>:<Menu/>}</button></div></nav>{open&&<nav id="mobile-menu" aria-label="Mobile navigation" className="absolute inset-x-0 top-[72px] grid gap-1 border-b border-[#d9b85f]/15 bg-[#070611] p-5 lg:hidden">{links.map(([label,href])=><Link key={label} href={href} onClick={()=>setOpen(false)} className="rounded-lg px-4 py-3 hover:bg-white/5">{label}</Link>)}<Link href="/login" className="px-4 py-3">Sign in</Link></nav>}</header>
}
