"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {ArrowLeft,ArrowRight,BookOpen,CalendarDays,CircleDollarSign,Database,Headphones,Megaphone,MessageCircle,MessageSquareText,PhoneMissed,Settings2,Send,Sparkles,Star,UserRoundCheck,X,Zap} from "lucide-react";
import {answerPublicQuestion} from "@/lib/marketing/public-faq";
import s from "./royal.module.css";
const services=[["AI Receptionist",Headphones],["Missed Call\nText Back",PhoneMissed],["Lead\nQualification",UserRoundCheck],["Instant\nFollow Up",Zap],["Appointment\nBooking",CalendarDays],["Unified\nInbox",MessageSquareText],["CRM",Database],["Payment\nLinks",CircleDollarSign],["Review\nRequests",Star],["Campaigns",Megaphone],["Knowledge\nBase",BookOpen],["Automations",Settings2]] as const;
export default function RoyalHero(){
 const [open,setOpen]=useState(false),[question,setQuestion]=useState("");
 const [messages,setMessages]=useState<{role:string;text:string}[]>([]);
 const rail=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null),log=useRef<HTMLDivElement>(null),launcher=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(open)input.current?.focus()},[open]);
 useEffect(()=>{log.current?.scrollTo({top:log.current.scrollHeight})},[messages]);
 function close(){setOpen(false);launcher.current?.focus()}
 function ask(value:string){const q=value.trim().slice(0,500);if(!q)return;setMessages(m=>[...m.slice(-18),{role:"user",text:q},{role:"assistant",text:answerPublicQuestion(q)}]);setQuestion("")}
 return <div className={s.page}><section className={s.stage} aria-label="J10 overview"><div className={s.hero} id="product">
 <div className={s.copy}><p className={s.eyebrow}>AI for service businesses</p><h1>Your AI operator<span>is already on it.</span></h1><p>Answers leads. Follows up. Books appointments.<br/>Helps collect payments. All on autopilot.</p><div className={s.cta}><Link href="/login?intent=signup&plan=growth&trial=1">Start Free <ArrowRight size={24}/></Link><p>72-hour free trial starts after Outcome Onboarding approval.</p></div></div>
 <div className={s.art}><div className={s.orbit} aria-hidden="true">{Array.from({length:16},(_,i)=><span key={i} className={s.dot} style={{left:`${50+50*Math.cos(i*Math.PI/8)}%`,top:`${50+50*Math.sin(i*Math.PI/8)}%`}}/>)}</div><Image src="/brand/j10-expression-excited.png" alt="J10 AI operator" width={1254} height={1254} unoptimized priority className={s.mascot}/><div className={s.node}><i><MessageCircle size={23}/></i><strong>AI receptionist</strong>Answers leads<br/>instantly</div><div className={s.node}><i><UserRoundCheck size={23}/></i><strong>Lead qualification</strong>Finds the<br/>right leads</div><div className={s.node}><i><CalendarDays size={23}/></i><strong>Appointment booking</strong>Schedules<br/>appointments</div><div className={s.node}><i><CircleDollarSign size={23}/></i><strong>Payments</strong>Helps collect<br/>payments</div></div>
 <aside className={s.conversation}><p className={s.example}>Example conversation</p><div className={s.message}><UserRoundCheck/><header><strong>New lead</strong><time>10:14 AM</time></header><div className={s.bubble}>Hi! Do you offer house cleaning service? I&apos;d like a quote.</div></div><div className={s.message}><Sparkles/><header><strong>J10 NEXUS</strong><time>10:15 AM</time></header><div className={s.bubble}>Hi! Yes, we do. I can help with a quote. What&apos;s your address and preferred cleaning date?</div></div><div className={s.message}><CalendarDays/><header><strong>Appointment booked</strong><time>10:18 AM</time></header><div className={s.bubble}>Great! You&apos;re confirmed for Saturday at 10:00 AM. We&apos;ll send a reminder the day before.</div></div><div className={s.message}><CircleDollarSign/><header><strong>Deposit request</strong><time>10:18 AM</time></header><div className={s.bubble}>To secure your booking, you can pay a deposit here:<span className={s.deposit}>Pay deposit with Stripe <ArrowRight size={17}/></span></div></div></aside>
 </div><div className={s.rail} id="services"><button aria-label="Scroll services left" onClick={()=>rail.current?.scrollBy({left:-260,behavior:"smooth"})}><ArrowLeft size={18}/></button><span className={s.railLabel}>What J10 can do</span><div className={s.scroller} ref={rail} tabIndex={0} role="region" aria-label="Service showcase"><div className={s.services}>{services.map(([label,Icon])=><div className={s.service} key={label}><Icon size={22}/><span>{label}</span></div>)}</div></div><button aria-label="Scroll services right" onClick={()=>rail.current?.scrollBy({left:260,behavior:"smooth"})}><ArrowRight size={18}/></button></div>
 <button className={s.launcher} ref={launcher} aria-expanded={open} aria-controls="j10-faq-chat" onClick={()=>setOpen(v=>!v)}><Image src="/brand/j10-expression-excited.png" alt="" width={44} height={44} unoptimized/><span>Ask J10<small>Questions &amp; signup help</small></span><ArrowRight size={17}/></button>
 {open&&<section id="j10-faq-chat" className={s.chat} role="region" aria-label="Ask J10" onKeyDown={e=>{if(e.key==="Escape")close()}}><header><div><strong>Ask J10</strong><small>Automated FAQ assistant</small></div><button onClick={close} aria-label="Close chat"><X size={20}/></button></header><div className={s.log} ref={log} role="log" aria-live="polite" aria-relevant="additions">{!messages.length&&<p>What would you like to know? I can help with plans, the trial, and signup. Please don&apos;t share private information.</p>}{messages.map((m,i)=><p key={i} className={m.role==="user"?s.user:undefined}><span className="sr-only">{m.role==="user"?"You":"J10"}: </span>{m.text}</p>)}</div><div className={s.suggestions}>{["Pricing","72-hour trial","Connections"].map(q=><button key={q} onClick={()=>ask(q)}>{q}</button>)}</div><form onSubmit={e=>{e.preventDefault();ask(question)}}><input ref={input} aria-label="Your question" placeholder="Ask a question" maxLength={500} value={question} onChange={e=>setQuestion(e.target.value)}/><button disabled={!question.trim()} aria-label="Send question"><Send size={18}/></button></form><small className="mt-3"><Link href="/pricing">Pricing</Link> · <Link href="/contact">Contact</Link></small></section>}
 </section></div>
}
