/**
 * J10 NEXUS TIER 4 — GENUINE ROI ATTRIBUTION
 * Quantifies concrete business value generated by autonomous AI agents,
 * linking agent execution traces to won CRM revenue, labor hours saved,
 * exact model compute costs, net ROI, and commercial multipliers.
 */

import { createServerSupabaseClient } from "@/lib/auth";
import type { AgentRoiAttribution, RoiAttributionSummary, AttributionType } from "@/types/governance";

const BLENDED_HOURLY_WAGE_USD = 45.0; // Standard enterprise employee cost per hour

export async function recordRoiAttribution(
  workspaceId: string,
  input: {
    agentId: string;
    traceId?: string;
    taskId?: string;
    contactId?: string;
    dealValueUsd?: number;
    hoursSaved?: number;
    modelCostUsd?: number;
    attributionType?: AttributionType;
  }
): Promise<AgentRoiAttribution> {
  const supabase = createServerSupabaseClient();

  const dealValue = input.dealValueUsd || 0.0;
  const hours = input.hoursSaved || 0.25; // 15 mins default per task
  const laborSavings = Number((hours * BLENDED_HOURLY_WAGE_USD).toFixed(2));
  const modelCost = input.modelCostUsd || 0.005;

  const grossValue = dealValue + laborSavings;
  const netRoi = Number((grossValue - modelCost).toFixed(2));
  const multiplier = modelCost > 0 ? Number((grossValue / modelCost).toFixed(2)) : 0;

  const { data, error } = await supabase
    .from("ai_agent_roi_attributions")
    .insert({
      workspace_id: workspaceId,
      agent_id: input.agentId,
      trace_id: input.traceId || null,
      task_id: input.taskId || null,
      contact_id: input.contactId || null,
      deal_value_usd: dealValue,
      hours_saved: hours,
      labor_savings_usd: laborSavings,
      model_cost_usd: modelCost,
      net_roi_usd: netRoi,
      roi_multiplier: multiplier,
      attribution_type: input.attributionType || (dealValue > 0 ? "won_deal" : "labor_saved"),
      created_at: new Date().toISOString(),
    })
    .select()
    .single();

  if (error || !data) {
    throw new Error(`Failed to record ROI attribution: ${error?.message || "Unknown error"}`);
  }

  return mapRoiRow(data);
}

export async function getWorkspaceRoiSummary(
  workspaceId: string
): Promise<RoiAttributionSummary> {
  const supabase = createServerSupabaseClient();

  const { data, error } = await supabase
    .from("ai_agent_roi_attributions")
    .select("*")
    .eq("workspace_id", workspaceId)
    .order("created_at", { ascending: false });

  if (error) {
    console.error("Error fetching ROI attributions:", error);
    return getZeroRoiSummary(workspaceId);
  }

  const rows = data || [];
  if (rows.length === 0) {
    return getZeroRoiSummary(workspaceId);
  }

  let totalRevenue = 0;
  let totalLaborSavings = 0;
  let totalComputeCost = 0;
  let totalHours = 0;

  const agentMap: Record<string, { gross: number; cost: number; name: string }> = {};

  for (const row of rows) {
    const deal = Number(row.deal_value_usd || 0);
    const labor = Number(row.labor_savings_usd || 0);
    const cost = Number(row.model_cost_usd || 0);
    const hrs = Number(row.hours_saved || 0);

    totalRevenue += deal;
    totalLaborSavings += labor;
    totalComputeCost += cost;
    totalHours += hrs;

    const agentId = row.agent_id;
    if (!agentMap[agentId]) {
      agentMap[agentId] = { gross: 0, cost: 0, name: formatAgentName(agentId) };
    }
    agentMap[agentId].gross += (deal + labor);
    agentMap[agentId].cost += cost;
  }

  const totalGrossValue = Number((totalRevenue + totalLaborSavings).toFixed(2));
  const netRoiUsd = Number((totalGrossValue - totalComputeCost).toFixed(2));
  const roiMultiplier = totalComputeCost > 0 ? Number((totalGrossValue / totalComputeCost).toFixed(1)) : 0;

  const topAgents = Object.entries(agentMap)
    .map(([agentId, stats]) => ({
      agentId,
      agentName: stats.name,
      grossValueUsd: Number(stats.gross.toFixed(2)),
      computeCostUsd: Number(stats.cost.toFixed(4)),
      netRoiUsd: Number((stats.gross - stats.cost).toFixed(2)),
      roiMultiplier: stats.cost > 0 ? Number((stats.gross / stats.cost).toFixed(1)) : 0,
    }))
    .sort((a, b) => b.netRoiUsd - a.netRoiUsd);

  return {
    workspaceId,
    totalAttributedRevenue: Number(totalRevenue.toFixed(2)),
    totalLaborSavings: Number(totalLaborSavings.toFixed(2)),
    totalGrossValue,
    totalComputeCost: Number(totalComputeCost.toFixed(4)),
    netRoiUsd,
    roiMultiplier,
    totalHoursSaved: Number(totalHours.toFixed(1)),
    attributionsCount: rows.length,
    topAgents,
  };
}

function getZeroRoiSummary(workspaceId: string): RoiAttributionSummary {
  return {
    workspaceId,
    totalAttributedRevenue: 0,
    totalLaborSavings: 0,
    totalGrossValue: 0,
    totalComputeCost: 0,
    netRoiUsd: 0,
    roiMultiplier: 0,
    totalHoursSaved: 0,
    attributionsCount: 0,
    topAgents: [],
  };
}

function formatAgentName(agentId: string): string {
  if (agentId === "sales-agent") return "Sarah Chen (Sales)";
  if (agentId === "support-agent") return "Aria Nexus (Support)";
  if (agentId === "marketing-agent") return "Alex Vance (Marketing)";
  if (agentId === "finance-agent") return "Marcus Sterling (Finance)";
  return agentId
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function mapRoiRow(row: any): AgentRoiAttribution {
  return {
    id: row.id,
    workspaceId: row.workspace_id,
    agentId: row.agent_id,
    traceId: row.trace_id,
    taskId: row.task_id,
    contactId: row.contact_id,
    dealValueUsd: Number(row.deal_value_usd || 0),
    hoursSaved: Number(row.hours_saved || 0),
    laborSavingsUsd: Number(row.labor_savings_usd || 0),
    modelCostUsd: Number(row.model_cost_usd || 0),
    netRoiUsd: Number(row.net_roi_usd || 0),
    roiMultiplier: Number(row.roi_multiplier || 0),
    attributionType: row.attribution_type as AttributionType,
    createdAt: row.created_at,
  };
}
