import type { RevenueCommandDashboardData } from "@/types/revenue-dashboard";

/**
 * Pure in-memory Demo Data fixture representing a realistic service business.
 * Reconciles the exact target figures:
 * - 47 new leads
 * - 26 qualified leads ($12,400 est.)
 * - 8 appointments booked ($8,940 open pipeline)
 * - 5 proposals sent ($5,200 active proposal value)
 * - 3 won deals ($2,480 verified revenue won)
 * - 11s average first response time
 * - 72.3% autonomous AI resolution rate
 * - 5 human handoffs (10.6%)
 *
 * GUARANTEED: This dataset is static and read-only. Zero records are written to Supabase.
 */
export const DEMO_REVENUE_DASHBOARD_DATA: RevenueCommandDashboardData = {
  workspaceId: "demo-workspace-apex-services",
  workspaceName: "Apex Commercial & Home Services",
  brandName: "Apex Services",
  isDemoMode: true,
  isEmptyWorkspace: false,
  dateRange: "30d",
  lastUpdated: new Date().toISOString(),

  snapshot: {
    newLeads: {
      value: 47,
      changePercentage: 18.5,
      changeLabel: "+18.5% vs prev period",
      isPositive: true,
      previousPeriodValue: 39,
      explanation: "Total inbound prospects captured across Telegram bot and website landing funnel.",
      destinationHref: "/dashboard/crm?status=New",
    },
    qualifiedLeads: {
      value: 26,
      changePercentage: 23.8,
      changeLabel: "55.3% qualification rate",
      isPositive: true,
      previousPeriodValue: 21,
      explanation: "High-intent leads scored >= 70 by the J10 AI Receptionist based on budget, timeline, and scope.",
      destinationHref: "/dashboard/crm?status=Qualified",
    },
    appointmentsBooked: {
      value: 8,
      changePercentage: 33.3,
      changeLabel: "+33.3% vs prev period",
      isPositive: true,
      previousPeriodValue: 6,
      explanation: "Qualified prospects who selected an appointment slot directly in conversation with AI.",
      destinationHref: "/dashboard/crm?stage=appointment",
    },
    pipelineValue: {
      value: "$8,940",
      changePercentage: 27.2,
      changeLabel: "+$1,910 new pipeline",
      isPositive: true,
      previousPeriodValue: "$7,030",
      explanation: "Cumulative estimated deal value of all active opportunities in Qualified, Appointment, and Proposal stages.",
      destinationHref: "/dashboard/revenue",
    },
    revenueWon: {
      value: "$2,480",
      changePercentage: 41.7,
      changeLabel: "3 closed deals",
      isPositive: true,
      previousPeriodValue: "$1,750",
      explanation: "Total payment-backed revenue collected and audited in the immutable ledger.",
      destinationHref: "/dashboard/revenue",
    },
    averageFirstResponseSeconds: {
      value: "11s",
      changePercentage: -88.5,
      changeLabel: "98% faster than human SLA",
      isPositive: true,
      previousPeriodValue: "14m",
      explanation: "Time from lead inbound message to AI Receptionist qualification response.",
      destinationHref: "/dashboard/bot-setup",
    },
  },

  funnel: {
    totalInbound: 47,
    overallConversionRate: 6.4, // 3 won / 47 = 6.38%
    averageTimeToWinDays: 4.2,
    stages: [
      {
        id: "new",
        label: "New Leads",
        count: 47,
        conversionFromPrevious: 100,
        conversionFromTotal: 100,
        pipelineValue: 23500,
        dropOffCount: 5,
        crmFilterHref: "/dashboard/crm?status=New",
      },
      {
        id: "contacted",
        label: "AI Contacted",
        count: 42,
        conversionFromPrevious: 89.4,
        conversionFromTotal: 89.4,
        pipelineValue: 21000,
        dropOffCount: 16,
        crmFilterHref: "/dashboard/crm?status=Contacted",
      },
      {
        id: "qualified",
        label: "AI Qualified",
        count: 26,
        conversionFromPrevious: 61.9,
        conversionFromTotal: 55.3,
        pipelineValue: 12400,
        dropOffCount: 18,
        crmFilterHref: "/dashboard/crm?status=Qualified",
      },
      {
        id: "appointment",
        label: "Appointment",
        count: 8,
        conversionFromPrevious: 30.8,
        conversionFromTotal: 17.0,
        pipelineValue: 8940,
        dropOffCount: 3,
        crmFilterHref: "/dashboard/crm?stage=appointment",
      },
      {
        id: "proposal",
        label: "Proposal Sent",
        count: 5,
        conversionFromPrevious: 62.5,
        conversionFromTotal: 10.6,
        pipelineValue: 5200,
        dropOffCount: 2,
        crmFilterHref: "/dashboard/crm?stage=proposal",
      },
      {
        id: "won",
        label: "Deals Won",
        count: 3,
        conversionFromPrevious: 60.0,
        conversionFromTotal: 6.4,
        pipelineValue: 2480,
        dropOffCount: 0,
        crmFilterHref: "/dashboard/crm?status=Won",
      },
    ],
  },

  aiReceptionist: {
    status: "active",
    statusReason: "AI Receptionist is actively responding across all connected channels.",
    conversationsHandled: 47,
    totalMessagesExchanged: 184,
    aiResolutionRate: 72.3, // 34 out of 47 handled without human intervention
    humanHandoffCount: 5,
    humanHandoffRate: 10.6,
    averageResponseTimeSeconds: 11,
    lastSuccessfulResponse: {
      contactName: "David Vance",
      channel: "Telegram Bot",
      timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    },
    knowledgeBaseHealth: {
      isHealthy: true,
      servicesCount: 4,
      hasPricing: true,
      hasBusinessHours: true,
      hasBookingLink: true,
      lastUpdated: "Today at 09:15 AM",
    },
    channels: [
      {
        channel: "telegram",
        label: "Telegram Official Bot",
        isConnected: true,
        status: "active",
        accountIdentifier: "@apex_services_bot",
      },
      {
        channel: "webchat",
        label: "Website Lead Funnel",
        isConnected: true,
        status: "active",
        accountIdentifier: "apexservices.com/contact",
      },
      {
        channel: "whatsapp",
        label: "WhatsApp (Coming Later)",
        isConnected: false,
        status: "unconfigured",
        accountIdentifier: "Coming Later",
      },
    ],
  },

  priorityLeads: [
    {
      id: "lead-1",
      contactId: "cnt-1",
      threadId: "thr-1",
      name: "Marcus Sterling",
      avatarUrl: "",
      email: "m.sterling@sterlinginvest.com",
      phone: "+1 (555) 234-8901",
      source: "telegram",
      qualificationScore: 94,
      intent: "Commercial Office Deep Clean (3-Story)",
      lastMessageSnippet: "Can you send the formal proposal for bi-weekly service starting next Monday?",
      lastMessageTimestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
      assignedOwner: "Human Operator",
      slaTimerText: "18m left",
      slaStatus: "warning",
      dealStage: "proposal",
      estimatedValue: 2400,
      recommendedNextAction: "Send Bi-Weekly Commercial Proposal",
      isUrgent: true,
    },
    {
      id: "lead-2",
      contactId: "cnt-2",
      threadId: "thr-2",
      name: "Elena Rostova",
      avatarUrl: "",
      email: "elena.r@crestviewlaw.org",
      phone: "+1 (555) 876-1204",
      source: "website",
      qualificationScore: 88,
      intent: "Emergency HVAC Diagnostic & Repair",
      lastMessageSnippet: "Our server room AC failed. Needs immediate technician dispatch.",
      lastMessageTimestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      assignedOwner: "Human Operator",
      slaTimerText: "5m left",
      slaStatus: "warning",
      dealStage: "appointment",
      estimatedValue: 1250,
      recommendedNextAction: "Confirm On-Site Tech Booking",
      isUrgent: true,
    },
    {
      id: "lead-3",
      contactId: "cnt-3",
      threadId: "thr-3",
      name: "David Vance",
      avatarUrl: "",
      email: "dvance@vantec.io",
      phone: "+1 (555) 432-6789",
      source: "telegram",
      qualificationScore: 82,
      intent: "Residential Full Home Remodel Inquiry",
      lastMessageSnippet: "What are your standard design consultation hours this Thursday?",
      lastMessageTimestamp: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
      assignedOwner: "AI Receptionist",
      slaTimerText: "Responded (11s)",
      slaStatus: "healthy",
      dealStage: "qualified",
      estimatedValue: 3800,
      recommendedNextAction: "Schedule Design Walkthrough",
      isUrgent: false,
    },
    {
      id: "lead-4",
      contactId: "cnt-4",
      threadId: "thr-4",
      name: "Sarah Jenkins",
      avatarUrl: "",
      email: "sjenkins@metroapartments.net",
      phone: "+1 (555) 901-3456",
      source: "telegram",
      qualificationScore: 76,
      intent: "Multi-Unit Property Maintenance Contract",
      lastMessageSnippet: "AI provided pricing sheet. Reviewing with HOA board tomorrow.",
      lastMessageTimestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
      assignedOwner: "AI Receptionist",
      slaTimerText: "Responded",
      slaStatus: "healthy",
      dealStage: "qualified",
      estimatedValue: 1490,
      recommendedNextAction: "Follow-up post HOA meeting",
      isUrgent: false,
    },
  ],

  recentActivity: [
    {
      id: "act-1",
      threadId: "thr-1",
      contactName: "Marcus Sterling",
      contactIdentifier: "@m_sterling_tg",
      channel: "telegram",
      latestMessage: "Can you send the formal proposal for bi-weekly service starting next Monday?",
      isAiHandled: false,
      sentiment: "positive",
      isUnread: true,
      timestamp: "12 mins ago",
      handoffStatus: "transferred",
    },
    {
      id: "act-2",
      threadId: "thr-2",
      contactName: "Elena Rostova",
      contactIdentifier: "elena.r@crestviewlaw.org",
      channel: "webchat",
      latestMessage: "Our server room AC failed. Needs immediate technician dispatch.",
      isAiHandled: false,
      sentiment: "urgent",
      isUnread: true,
      timestamp: "25 mins ago",
      handoffStatus: "requested",
    },
    {
      id: "act-3",
      threadId: "thr-3",
      contactName: "David Vance",
      contactIdentifier: "+1 (555) 432-6789",
      channel: "telegram",
      latestMessage: "AI answered pricing and offered Thursday 2:00 PM appointment slot.",
      isAiHandled: true,
      sentiment: "positive",
      isUnread: false,
      timestamp: "42 mins ago",
      handoffStatus: "none",
    },
    {
      id: "act-4",
      threadId: "thr-5",
      contactName: "Apex Property Group",
      contactIdentifier: "+1 (555) 678-9012",
      channel: "telegram",
      latestMessage: "Payment verified: $980.00 for Monthly Facilities Package.",
      isAiHandled: true,
      sentiment: "positive",
      isUnread: false,
      timestamp: "2 hours ago",
      handoffStatus: "resolved",
    },
    {
      id: "act-5",
      threadId: "thr-4",
      contactName: "Sarah Jenkins",
      contactIdentifier: "sjenkins@metroapartments.net",
      channel: "telegram",
      latestMessage: "AI provided pricing sheet. Reviewing with HOA board tomorrow.",
      isAiHandled: true,
      sentiment: "neutral",
      isUnread: false,
      timestamp: "3 hours ago",
      handoffStatus: "none",
    },
  ],

  appointments: {
    today: [
      {
        id: "apt-1",
        contactId: "cnt-2",
        clientName: "Elena Rostova (Crestview Law)",
        serviceRequested: "Emergency HVAC Diagnostic",
        dateTimeFormatted: "Today, 3:30 PM",
        timeFormatted: "3:30 PM",
        dateISO: new Date().toISOString(),
        status: "confirmed",
        isToday: true,
        estimatedValue: 1250,
      },
      {
        id: "apt-2",
        contactId: "cnt-6",
        clientName: "Robert Chen (Oakridge Clinic)",
        serviceRequested: "Quarterly Air Quality Audit",
        dateTimeFormatted: "Today, 5:00 PM",
        timeFormatted: "5:00 PM",
        dateISO: new Date().toISOString(),
        status: "confirmed",
        isToday: true,
        estimatedValue: 750,
      },
    ],
    upcoming: [
      {
        id: "apt-3",
        contactId: "cnt-3",
        clientName: "David Vance",
        serviceRequested: "Design Consultation & Walkthrough",
        dateTimeFormatted: "Tomorrow, 2:00 PM",
        timeFormatted: "2:00 PM",
        dateISO: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
        status: "pending",
        isToday: false,
        estimatedValue: 3800,
      },
      {
        id: "apt-4",
        contactId: "cnt-7",
        clientName: "Highland Retail Plaza",
        serviceRequested: "Commercial Pressure Washing Review",
        dateTimeFormatted: "Friday, 10:00 AM",
        timeFormatted: "10:00 AM",
        dateISO: new Date(Date.now() + 3 * 24 * 3600 * 1000).toISOString(),
        status: "confirmed",
        isToday: false,
        estimatedValue: 1800,
      },
    ],
    leadsAwaitingFollowupCount: 3,
    missedOverdueActionsCount: 0,
    bookingConversionRate: 30.8, // 8 appointments from 26 qualified leads
  },

  revenueAttribution: {
    revenueWon: 2480,
    openPipelineValue: 8940,
    aiInfluencedRevenue: 2480, // 100% of closed deals originated or touched by AI receptionist
    aiInfluencePercentage: 100,
    bySource: [
      {
        source: "telegram",
        label: "Telegram Bot DM",
        leadsCount: 29,
        wonCount: 2,
        wonRevenue: 1480,
        pipelineValue: 5890,
        conversionRate: 6.9,
      },
      {
        source: "website",
        label: "Website Lead Funnel",
        leadsCount: 15,
        wonCount: 1,
        wonRevenue: 1000,
        pipelineValue: 2450,
        conversionRate: 6.7,
      },
      {
        source: "manual",
        label: "Direct & Inbound Phone",
        leadsCount: 3,
        wonCount: 0,
        wonRevenue: 0,
        pipelineValue: 600,
        conversionRate: 0.0,
      },
    ],
    recentWonDeals: [
      {
        id: "deal-1",
        clientName: "Apex Property Group",
        serviceName: "Monthly Facilities Package",
        amount: 980,
        wonDate: "Today",
        leadSource: "Telegram Bot",
        verifiedInLedger: true,
      },
      {
        id: "deal-2",
        clientName: "Summit Dental Clinic",
        serviceName: "Deep Sanitization Service",
        amount: 850,
        wonDate: "3 days ago",
        leadSource: "Website Funnel",
        verifiedInLedger: true,
      },
      {
        id: "deal-3",
        clientName: "Kensington Lofts",
        serviceName: "HVAC Spring Overhaul",
        amount: 650,
        wonDate: "6 days ago",
        leadSource: "Telegram Bot",
        verifiedInLedger: true,
      },
    ],
    topPerformingService: {
      name: "Monthly Facilities Maintenance Package",
      revenue: 980,
      dealCount: 1,
    },
  },

  recommendedActions: [
    {
      id: "rec-1",
      priority: "high",
      category: "lead",
      title: "Proposal Ready for Marcus Sterling",
      reason: "Lead scored 94/100 and explicitly requested bi-weekly commercial proposal via Telegram.",
      expectedValue: "$2,400 deal value",
      actionLabel: "Review in CRM",
      actionHref: "/dashboard/crm?status=Qualified",
      dismissible: true,
    },
    {
      id: "rec-2",
      priority: "high",
      category: "handoff",
      title: "Human Operator Requested: Elena Rostova",
      reason: "Emergency server room HVAC issue requiring priority technician dispatch.",
      expectedValue: "$1,250 repair value",
      actionLabel: "Take Over in Inbox",
      actionHref: "/dashboard/inbox",
      dismissible: true,
    },
    {
      id: "rec-3",
      priority: "medium",
      category: "appointment",
      title: "Confirm Tomorrow's Booking for David Vance",
      reason: "Pending walkthrough requested for Thursday at 2:00 PM.",
      expectedValue: "$3,800 remodel pipeline",
      actionLabel: "Confirm Appointment",
      actionHref: "/dashboard/crm",
      dismissible: true,
    },
    {
      id: "rec-4",
      priority: "low",
      category: "setup",
      title: "Add Weekend Emergency Pricing to Bot Setup",
      reason: "3 prospects inquired about Sunday emergency rates in the last 7 days.",
      actionLabel: "Update Services in Bot Setup",
      actionHref: "/dashboard/bot-setup",
      dismissible: true,
    },
  ],

  planUsage: {
    planTier: "growth",
    planName: "Growth Tier (AI Receptionist + CRM)",
    priceMonthly: 149,
    status: "active",
    aiConversationsUsed: 184,
    aiConversationsLimit: 1000,
    leadsUsed: 47,
    leadsLimit: 250,
    channelsConnected: 2,
    channelsLimit: 3,
    renewsAt: "Oct 1, 2026",
  },
};
