export interface IntegrationDrawerData {
  id: string;
  name: string;
  slug: string;
  category: string;
  status: "Available" | "Next" | "Roadmap";
  description: string;
  triggers: string[];
  actions: string[];
  scopes: string[];
  howItWorks: string;
  authMethod: string;
}

export const ALL_42_INTEGRATIONS: IntegrationDrawerData[] = [
  // Messaging
  {
    id: "whatsapp-business",
    name: "WhatsApp Business",
    slug: "whatsapp",
    category: "Messaging",
    status: "Available",
    description: "Connect Meta WhatsApp Cloud API or 360dialog for 24/7 AI Receptionist conversations, automated qualification, and payment links.",
    triggers: ["Incoming message received", "Message status updated (delivered, read)", "Customer media / audio message received"],
    actions: ["Send AI response message", "Send approved template", "Send Stripe payment link", "Route to human team"],
    scopes: ["whatsapp_business_messaging", "whatsapp_business_management"],
    howItWorks: "J10 connects to your official WhatsApp Business number via Meta Cloud API or coexistence mode, qualifying leads and booking appointments in chat.",
    authMethod: "Meta Embedded Signup / System User Token",
  },
  {
    id: "telegram",
    name: "Telegram",
    slug: "telegram",
    category: "Messaging",
    status: "Available",
    description: "Operate Telegram Secretary Mode for personal business DMs or deploy dedicated branded bots with Stripe-gated VIP group access.",
    triggers: ["Telegram DM received", "VIP channel join request", "Bot command triggered", "Group message received"],
    actions: ["Send AI Autopilot reply", "Approve VIP channel access", "Create appointment booking", "Dispatch payment request"],
    scopes: ["Bot API access", "Business Secretary Connection Rights"],
    howItWorks: "One-click connection via @BotFather token or Secretary Mode linking. J10 operates as your instant 24/7 assistant.",
    authMethod: "Bot API Token / Telegram Business Link",
  },
  {
    id: "instagram-business",
    name: "Instagram",
    slug: "instagram",
    category: "Messaging",
    status: "Next",
    description: "Capture direct message inquiries, story replies, and comment leads automatically.",
    triggers: ["Direct Message received", "Story mention received", "Post comment submitted"],
    actions: ["Send instant DM reply", "Send booking link", "Qualify customer budget & timing"],
    scopes: ["instagram_basic", "instagram_manage_messages", "pages_show_list"],
    howItWorks: "Connect your Instagram Professional account to automatically answer DM inquiries and turn comments into scheduled calls.",
    authMethod: "Meta OAuth 2.0",
  },
  {
    id: "messenger",
    name: "Messenger",
    slug: "messenger",
    category: "Messaging",
    status: "Next",
    description: "Automate Facebook Page conversations and customer support routing.",
    triggers: ["Page message received", "Post comment added"],
    actions: ["Send AI reply", "Dispatch booking proposal", "Notify manager"],
    scopes: ["pages_messaging", "pages_read_engagement"],
    howItWorks: "Direct Meta Graph connection to respond to Facebook page visitors within seconds.",
    authMethod: "Meta OAuth 2.0",
  },

  // Voice & SMS
  {
    id: "twilio",
    name: "Twilio",
    slug: "twilio",
    category: "Voice & SMS",
    status: "Next",
    description: "Automate SMS follow-ups, missed-call text-backs, and phone number verification.",
    triggers: ["Inbound SMS received", "Missed call detected", "Call completed"],
    actions: ["Send immediate text-back", "Initiate voice qualification", "Send SMS appointment reminder"],
    scopes: ["Twilio Account SID & Auth Token"],
    howItWorks: "When a customer calls and you miss it, J10 instantly texts them back within 10 seconds to capture and qualify the opportunity.",
    authMethod: "Twilio API Credentials",
  },
  {
    id: "telnyx",
    name: "Telnyx",
    slug: "telnyx",
    category: "Voice & SMS",
    status: "Roadmap",
    description: "Enterprise telephony, SMS messaging, and programmable voice numbers.",
    triggers: ["Inbound SMS received", "Call state changed"],
    actions: ["Send SMS", "Initiate programmable voice call"],
    scopes: ["Telnyx API Key"],
    howItWorks: "Direct carrier connectivity for high-volume SMS and voice routing.",
    authMethod: "Telnyx API Key",
  },

  // Email
  {
    id: "gmail",
    name: "Gmail",
    slug: "gmail",
    category: "Email",
    status: "Next",
    description: "Receive, summarize, draft, and send customer follow-up emails via Google Workspace.",
    triggers: ["New customer email received", "Thread reply received"],
    actions: ["Draft AI response", "Send confirmation email", "Add lead labels"],
    scopes: ["https://www.googleapis.com/auth/gmail.send", "https://www.googleapis.com/auth/gmail.modify"],
    howItWorks: "Secure Google OAuth connection that synchronizes inbound inquiries with the unified lead inbox.",
    authMethod: "Google OAuth 2.0",
  },
  {
    id: "outlook-mail",
    name: "Microsoft Outlook",
    slug: "microsoftoutlook",
    category: "Email",
    status: "Next",
    description: "Connect Microsoft 365 to handle business emails and follow-up threads.",
    triggers: ["New email received", "Thread updated"],
    actions: ["Send email", "Reply to customer", "Assign folder category"],
    scopes: ["Mail.ReadWrite", "Mail.Send", "offline_access"],
    howItWorks: "Microsoft Graph API integration for enterprise email management.",
    authMethod: "Microsoft OAuth 2.0",
  },

  // Scheduling
  {
    id: "google-calendar",
    name: "Google Calendar",
    slug: "googlecalendar",
    category: "Scheduling",
    status: "Next",
    description: "Check live appointment availability, resolve booking conflicts, and place events automatically.",
    triggers: ["Event scheduled", "Event cancelled / rescheduled", "Free slot requested"],
    actions: ["Check real-time availability", "Create calendar event", "Send invite to customer"],
    scopes: ["https://www.googleapis.com/auth/calendar.events"],
    howItWorks: "J10 AI checks your real calendar in real time and books clients without double-booking.",
    authMethod: "Google OAuth 2.0",
  },
  {
    id: "outlook-calendar",
    name: "Outlook Calendar",
    slug: "microsoftoutlook",
    category: "Scheduling",
    status: "Next",
    description: "Synchronize appointments with Microsoft 365 / Outlook calendars.",
    triggers: ["Meeting requested", "Calendar event modified"],
    actions: ["Create Outlook event", "Query free/busy slots", "Update meeting attendees"],
    scopes: ["Calendars.ReadWrite", "offline_access"],
    howItWorks: "Direct Microsoft Graph integration for automated business scheduling.",
    authMethod: "Microsoft OAuth 2.0",
  },
  {
    id: "calendly",
    name: "Calendly",
    slug: "calendly",
    category: "Scheduling",
    status: "Next",
    description: "Dispatch customized scheduling links and trigger J10 workflow sequences when bookings occur.",
    triggers: ["Invitee created", "Invitee cancelled"],
    actions: ["Generate custom booking link", "Send SMS confirmation", "Update CRM lead status"],
    scopes: ["default:read", "default:write"],
    howItWorks: "Webhook synchronization with Calendly event types to qualify leads before scheduling.",
    authMethod: "Calendly OAuth 2.0",
  },
  {
    id: "acuity-scheduling",
    name: "Acuity Scheduling",
    slug: "acuityscheduling",
    category: "Scheduling",
    status: "Roadmap",
    description: "Appointment scheduling and intake form processing for service businesses.",
    triggers: ["Appointment scheduled", "Appointment rescheduled", "Intake form submitted"],
    actions: ["Create appointment", "Cancel appointment", "Fetch service list"],
    scopes: ["Acuity User ID & API Key"],
    howItWorks: "Squarespace Acuity API connection to coordinate appointment slots with payments.",
    authMethod: "Acuity API Credentials",
  },

  // Payments
  {
    id: "stripe",
    name: "Stripe",
    slug: "stripe",
    category: "Payments",
    status: "Available",
    description: "Create instant checkout sessions, verify customer payment completion, and unlock premium deliverables.",
    triggers: ["checkout.session.completed", "payment_intent.succeeded", "customer.subscription.created", "invoice.payment_failed"],
    actions: ["Generate Stripe Checkout Link", "Create customer profile", "Grant VIP Telegram access", "Generate invoice receipt"],
    scopes: ["read_write", "webhook_signing"],
    howItWorks: "J10 automatically generates secure Stripe payment links in WhatsApp or Telegram conversations and verifies completion.",
    authMethod: "Stripe Connect / Restricted Secret Key",
  },
  {
    id: "square",
    name: "Square",
    slug: "square",
    category: "Payments",
    status: "Roadmap",
    description: "Process in-person and digital payments, inventory lookups, and customer profiles.",
    triggers: ["Payment completed", "Order created", "Refund processed"],
    actions: ["Create Square checkout link", "Fetch customer catalog", "Record transaction"],
    scopes: ["PAYMENTS_WRITE", "ORDERS_WRITE", "CUSTOMERS_READ"],
    howItWorks: "Square REST API connection for local storefront and mobile point-of-sale payment sync.",
    authMethod: "Square OAuth 2.0",
  },
  {
    id: "paypal",
    name: "PayPal",
    slug: "paypal",
    category: "Payments",
    status: "Next",
    description: "Accept global payments and manage subscription billing seamlessly.",
    triggers: ["Payment capture completed", "Subscription activated"],
    actions: ["Generate PayPal invoice link", "Verify payment status", "Send receipt"],
    scopes: ["https://uri.paypal.com/services/invoicing", "https://uri.paypal.com/services/payments/realtimepayment"],
    howItWorks: "PayPal v2 Checkout and Invoicing API synchronization.",
    authMethod: "PayPal REST API Client Credentials",
  },

  // CRM
  {
    id: "hubspot",
    name: "HubSpot",
    slug: "hubspot",
    category: "CRM",
    status: "Next",
    description: "Create and update contacts, deals, notes, and lifecycle stages in real time as leads converse with J10.",
    triggers: ["Contact created", "Deal stage updated", "Form submitted"],
    actions: ["Create contact", "Create deal with revenue value", "Add conversation activity timeline note"],
    scopes: ["crm.objects.contacts.read", "crm.objects.contacts.write", "crm.objects.deals.read", "crm.objects.deals.write"],
    howItWorks: "Every time a customer interacts with J10, their contact details, budget, and summary notes sync into HubSpot.",
    authMethod: "HubSpot OAuth 2.0 App",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    slug: "salesforce",
    category: "CRM",
    status: "Roadmap",
    description: "Enterprise CRM synchronization for Leads, Contacts, Opportunities, and Custom Objects.",
    triggers: ["Lead created", "Opportunity closed/won", "Task assigned"],
    actions: ["Upsert Lead record", "Create Opportunity", "Log call record"],
    scopes: ["api", "refresh_token", "offline_access"],
    howItWorks: "Salesforce Connected App with REST API integration.",
    authMethod: "Salesforce OAuth 2.0 Connected App",
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    slug: "pipedrive",
    category: "CRM",
    status: "Next",
    description: "Pipeline management for sales deals, activities, and lead stages.",
    triggers: ["Deal moved stage", "Person created", "Activity completed"],
    actions: ["Create Pipedrive deal", "Add deal note", "Schedule sales activity"],
    scopes: ["deals:full", "contacts:full", "activities:full"],
    howItWorks: "Syncs qualified opportunities directly into your designated sales pipeline stage.",
    authMethod: "Pipedrive OAuth 2.0",
  },
  {
    id: "clickup",
    name: "ClickUp",
    slug: "clickup",
    category: "CRM",
    status: "Roadmap",
    description: "Task creation, project boarding, and client onboarding workflows.",
    triggers: ["Task created", "Status changed", "Checklist item checked"],
    actions: ["Create client onboarding task", "Assign team member", "Post task comment"],
    scopes: ["Task Read & Write", "Space Access"],
    howItWorks: "Turns booked client appointments into structured project tasks with due dates.",
    authMethod: "ClickUp OAuth 2.0 / API Token",
  },

  // Commerce
  {
    id: "shopify",
    name: "Shopify",
    slug: "shopify",
    category: "Commerce",
    status: "Next",
    description: "Look up order tracking, check product inventory, and send abandoned cart follow-up offers.",
    triggers: ["orders/create", "orders/fulfilled", "checkouts/create", "customers/create"],
    actions: ["Query order tracking status", "Query product availability & price", "Create draft order / discount link"],
    scopes: ["read_orders", "write_orders", "read_products", "read_customers"],
    howItWorks: "Customers can ask 'Where is my order?' in WhatsApp/Telegram, and J10 retrieves live tracking immediately.",
    authMethod: "Shopify App OAuth 2.0",
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    slug: "woocommerce",
    category: "Commerce",
    status: "Next",
    description: "Sync WordPress WooCommerce store orders, products, and customer queries.",
    triggers: ["woocommerce_new_order", "woocommerce_order_status_completed"],
    actions: ["Get order details", "Search products", "Create coupon code"],
    scopes: ["read_write"],
    howItWorks: "REST API connection with customer secret keys to provide instant shopping support in chat.",
    authMethod: "WooCommerce REST API Consumer Key & Secret",
  },

  // Accounting
  {
    id: "quickbooks",
    name: "QuickBooks",
    slug: "quickbooks",
    category: "Accounting",
    status: "Next",
    description: "Create customer invoices, sync payments received, and keep accounting books up to date.",
    triggers: ["Invoice created", "Payment received"],
    actions: ["Generate QuickBooks invoice", "Create customer profile", "Record paid transaction"],
    scopes: ["com.intuit.quickbooks.accounting"],
    howItWorks: "Intuit OAuth connection to log client sales and payments directly into QuickBooks Online.",
    authMethod: "Intuit QuickBooks OAuth 2.0",
  },
  {
    id: "xero",
    name: "Xero",
    slug: "xero",
    category: "Accounting",
    status: "Roadmap",
    description: "Cloud accounting integration for invoicing, bills, and payment reconciliation.",
    triggers: ["Invoice status changed", "Contact updated"],
    actions: ["Create Xero sales invoice", "Send invoice to client", "Mark invoice as paid"],
    scopes: ["accounting.transactions", "accounting.contacts"],
    howItWorks: "Xero API connection to synchronize customer accounts and billing records.",
    authMethod: "Xero OAuth 2.0",
  },

  // Marketing & Leads
  {
    id: "meta-lead-ads",
    name: "Meta Lead Ads",
    slug: "meta",
    category: "Marketing & Leads",
    status: "Next",
    description: "Instantaneous webhook capture from Facebook & Instagram Instant Forms with immediate 10-second SMS/WhatsApp outreach.",
    triggers: ["leadgen_lead_created (Webhook)"],
    actions: ["Parse form fields", "Trigger instant 24/7 AI outreach", "Push lead to CRM & inbox"],
    scopes: ["leads_retrieval", "pages_manage_ads", "pages_show_list"],
    howItWorks: "When a potential buyer fills out a Meta lead form, J10 contacts them within seconds before they leave their phone.",
    authMethod: "Meta Graph API Webhook & Page Token",
  },
  {
    id: "google-ads",
    name: "Google Ads",
    slug: "googleads",
    category: "Marketing & Leads",
    status: "Next",
    description: "Track conversion value, sync offline conversion events, and capture Google Lead Form submissions.",
    triggers: ["Lead form extension submitted"],
    actions: ["Upload offline conversion adjustment", "Trigger immediate outreach"],
    scopes: ["https://www.googleapis.com/auth/adwords"],
    howItWorks: "Matches converted paying clients back to Google Click IDs (GCLID) for maximum ad return on investment.",
    authMethod: "Google Ads OAuth 2.0",
  },
  {
    id: "wordpress",
    name: "WordPress",
    slug: "wordpress",
    category: "Marketing & Leads",
    status: "Roadmap",
    description: "Embed J10 chat widgets, capture contact form entries, and publish content updates.",
    triggers: ["Form entry submitted (CF7, Gravity Forms, WPForms)"],
    actions: ["Route submission to AI receptionist", "Create lead profile"],
    scopes: ["REST API Application Password"],
    howItWorks: "WordPress REST API integration to synchronize web visitors with your unified communication hub.",
    authMethod: "WordPress REST API / Plugin Token",
  },
  {
    id: "typeform",
    name: "Typeform",
    slug: "typeform",
    category: "Marketing & Leads",
    status: "Next",
    description: "Qualify high-value prospects through interactive multi-step forms and questionnaires.",
    triggers: ["form_response (Webhook)"],
    actions: ["Analyze answers with AI", "Score lead readiness", "Send personalized WhatsApp/Email greeting"],
    scopes: ["forms:read", "responses:read", "webhooks:write"],
    howItWorks: "Instantly ingests Typeform submissions and initiates a tailored AI follow-up based on user answers.",
    authMethod: "Typeform OAuth 2.0 / Personal Token",
  },
  {
    id: "jotform",
    name: "Jotform",
    slug: "jotform",
    category: "Marketing & Leads",
    status: "Roadmap",
    description: "Process custom intake documents, liability waivers, and contract agreements.",
    triggers: ["Form submission received"],
    actions: ["Extract signed PDF", "Update customer profile", "Confirm appointment"],
    scopes: ["readOnly", "fullAccess"],
    howItWorks: "Jotform API integration for document intake and lead qualification.",
    authMethod: "Jotform API Key",
  },

  // Reviews
  {
    id: "google-business-profile",
    name: "Google Business Profile",
    slug: "google",
    category: "Reviews",
    status: "Next",
    description: "Automate 5-star review request sequences via WhatsApp/SMS and monitor new public Google reviews.",
    triggers: ["New Google Review posted", "Review rating updated"],
    actions: ["Draft AI review response", "Send review invite link to satisfied customers", "Alert team on negative feedback"],
    scopes: ["https://www.googleapis.com/auth/business.manage"],
    howItWorks: "After a job or appointment is completed, J10 sends a friendly link to boost your local Google Maps ranking.",
    authMethod: "Google My Business OAuth 2.0",
  },

  // Files & Data
  {
    id: "google-drive",
    name: "Google Drive",
    slug: "googledrive",
    category: "Files & Data",
    status: "Next",
    description: "Upload customer files, store signed agreements, and retrieve company knowledge documents.",
    triggers: ["File created / modified"],
    actions: ["Upload client photos/files", "Search folder", "Index document into AI Knowledge Base"],
    scopes: ["https://www.googleapis.com/auth/drive.file"],
    howItWorks: "Files shared by customers in chat are automatically archived into organized customer folders in Google Drive.",
    authMethod: "Google OAuth 2.0",
  },
  {
    id: "google-sheets",
    name: "Google Sheets",
    slug: "googlesheets",
    category: "Files & Data",
    status: "Next",
    description: "Log leads, sales, expenses, and customer records into live collaborative spreadsheets.",
    triggers: ["Row added / modified"],
    actions: ["Append row with lead details", "Lookup customer row", "Update cell value"],
    scopes: ["https://www.googleapis.com/auth/spreadsheets"],
    howItWorks: "Real-time 2-way sync to log every inquiry into your existing tracking spreadsheet.",
    authMethod: "Google OAuth 2.0",
  },
  {
    id: "microsoft-onedrive",
    name: "Microsoft OneDrive",
    slug: "microsoftonedrive",
    category: "Files & Data",
    status: "Next",
    description: "Secure cloud storage in Microsoft 365 for business documents and intake attachments.",
    triggers: ["Item created / updated"],
    actions: ["Upload file", "Create sharing link", "Organize customer folder"],
    scopes: ["Files.ReadWrite", "offline_access"],
    howItWorks: "Microsoft Graph API integration for corporate file storage.",
    authMethod: "Microsoft OAuth 2.0",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    slug: "dropbox",
    category: "Files & Data",
    status: "Next",
    description: "Sync customer assets, project estimates, and media files to Dropbox folders.",
    triggers: ["File uploaded"],
    actions: ["Upload document", "Generate shared link"],
    scopes: ["files.content.write", "files.content.read"],
    howItWorks: "Dropbox API v2 integration for asset archiving.",
    authMethod: "Dropbox OAuth 2.0",
  },

  // Team
  {
    id: "slack",
    name: "Slack",
    slug: "slack",
    category: "Team",
    status: "Next",
    description: "Send live lead notifications, escalate high-priority customer chats, and allow staff to reply via Slack channels.",
    triggers: ["Staff message posted in escalation channel", "Slash command invoked"],
    actions: ["Post new lead alert with full summary", "Send direct message to on-call manager", "Update channel status"],
    scopes: ["chat:write", "channels:read", "commands", "incoming-webhook"],
    howItWorks: "Your team stays inside Slack while J10 handles external customer conversations on WhatsApp and Telegram.",
    authMethod: "Slack OAuth 2.0 / Bot Token",
  },
  {
    id: "microsoft-teams",
    name: "Microsoft Teams",
    slug: "microsoftteams",
    category: "Team",
    status: "Next",
    description: "Notify staff channels in Microsoft 365 when new deals or VIP bookings occur.",
    triggers: ["Channel message received"],
    actions: ["Post adaptive card with lead details", "Notify assigned technician"],
    scopes: ["ChatMessage.Send", "ChannelMessage.Send"],
    howItWorks: "Microsoft Graph Teams integration for internal team coordination.",
    authMethod: "Microsoft OAuth 2.0",
  },

  // Automation
  {
    id: "zapier",
    name: "Zapier",
    slug: "zapier",
    category: "Automation",
    status: "Next",
    description: "Connect J10 to 6,000+ business applications with instant trigger events and actions.",
    triggers: ["J10 Lead Qualified", "J10 Appointment Booked", "J10 Payment Received", "J10 Escalation Triggered"],
    actions: ["Create J10 Lead", "Send J10 Outbound Message", "Update J10 Knowledge Base"],
    scopes: ["zapier:partner_api"],
    howItWorks: "Official Zapier integration app for multi-step no-code workflow orchestration.",
    authMethod: "Zapier OAuth 2.0 / API Key",
  },
  {
    id: "make",
    name: "Make",
    slug: "make",
    category: "Automation",
    status: "Next",
    description: "Visual workflow automation platform with modular scenario builders.",
    triggers: ["Webhook trigger", "Data watch"],
    actions: ["Execute custom scenario", "Route variables"],
    scopes: ["make:scenarios"],
    howItWorks: "Custom Make (Integromat) modules to orchestrate intricate business logic.",
    authMethod: "Make API Key / Custom App",
  },
  {
    id: "n8n",
    name: "n8n",
    slug: "n8n",
    category: "Automation",
    status: "Roadmap",
    description: "Fair-code self-hosted workflow automation for enterprise privacy and custom nodes.",
    triggers: ["n8n Webhook"],
    actions: ["Trigger node workflow", "Return JSON payload"],
    scopes: ["n8n API Key"],
    howItWorks: "Direct HTTP and community node integration for self-hosted infrastructures.",
    authMethod: "n8n API Key",
  },
  {
    id: "webhooks-api",
    name: "Webhooks & API",
    slug: "webhooks",
    category: "Automation",
    status: "Available",
    description: "Custom inbound and outbound webhooks with HMAC-SHA256 signature verification and complete OpenAPI documentation.",
    triggers: ["Inbound custom JSON webhook received", "Outbound event dispatch"],
    actions: ["Send outbound POST request with payload", "Transform JSON schema", "Verify signature"],
    scopes: ["api:sandbox", "api:webhooks_manage"],
    howItWorks: "Developer-friendly REST endpoints to connect any custom CRM, backend, or legacy proprietary software.",
    authMethod: "HMAC Secret Key / Bearer Token",
  },

  // Field Services
  {
    id: "jobber",
    name: "Jobber",
    slug: "jobber",
    category: "Field Services",
    status: "Roadmap",
    description: "Home service operations management for quotes, jobs, invoices, and dispatching.",
    triggers: ["Quote accepted", "Job completed", "Invoice paid"],
    actions: ["Create client in Jobber", "Generate quote draft", "Schedule job visit"],
    scopes: ["clients:read", "clients:write", "jobs:read", "jobs:write"],
    howItWorks: "Connects HVAC, plumbing, cleaning, and contractor businesses directly to J10 AI Receptionist.",
    authMethod: "Jobber OAuth 2.0",
  },
  {
    id: "housecall-pro",
    name: "Housecall Pro",
    slug: "housecallpro",
    category: "Field Services",
    status: "Roadmap",
    description: "Field service software for scheduling, dispatching, and customer communication.",
    triggers: ["Job created", "Customer created", "Payment captured"],
    actions: ["Create customer", "Book job on calendar", "Add job note"],
    scopes: ["customers.read", "customers.write", "jobs.read", "jobs.write"],
    howItWorks: "Syncs field technician schedules and customer calls seamlessly.",
    authMethod: "Housecall Pro API Key",
  },
  {
    id: "mindbody",
    name: "Mindbody",
    slug: "mindbody",
    category: "Field Services",
    status: "Roadmap",
    description: "Fitness studio, spa, and wellness appointment scheduling and class booking.",
    triggers: ["Class booked", "Client created", "Membership renewed"],
    actions: ["Book class slot", "Check schedule availability", "Process client checkout"],
    scopes: ["Client", "Appointment", "Class"],
    howItWorks: "Mindbody Public API connection for gym, yoga, and wellness client booking.",
    authMethod: "Mindbody Public API Credentials",
  },
];
