import "server-only";

import type {
  IntegrationConnectorRuntimeAdapter,
  IntegrationRuntimeActionInvocation,
  IntegrationRuntimeHealthResult,
  IntegrationRuntimeInvocationContext,
  IntegrationRuntimeResult,
} from "@/types/integration-runtime";
import {
  INTEGRATION_RUNTIME_SCHEMA_VERSION,
  IntegrationRuntimeError,
} from "@/types/integration-runtime";

const REQUEST_TIMEOUT_MS = 15_000;
const PAYPAL_API_BASE = "https://api-m.paypal.com";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function extractString(input: Record<string, unknown>, key: string, label: string): string {
  const val = input[key];
  if (typeof val !== "string" || !val.trim()) {
    throw new IntegrationRuntimeError(`${label} is required.`, {
      code: "INVALID_PAYPAL_INPUT",
      category: "validation",
      status: 400,
    });
  }
  return val.trim();
}

async function readPayPalCredentials(
  context: IntegrationRuntimeInvocationContext,
): Promise<{ token: string; payerId?: string }> {
  const creds = await context.credentials.read(["access_token", "payer_id"]);
  const token = creds.access_token;

  if (!token) {
    throw new IntegrationRuntimeError("PayPal access token is missing.", {
      code: "PAYPAL_AUTH_MISSING",
      category: "authentication",
      status: 401,
    });
  }

  return { token, payerId: creds.payer_id };
}

async function executePayPalAction(
  invocation: IntegrationRuntimeActionInvocation,
): Promise<IntegrationRuntimeResult> {
  const { capabilityId, input, mode } = invocation;
  const inputObj = isRecord(input) ? input : {};

  if (mode === "sandbox" || mode === "simulate") {
    return {
      success: true,
      responseStatus: 200,
      providerRequestId: `sim_paypal_${Date.now()}`,
      rateLimit: null,
      metadata: {
        mode,
        simulated: true,
        capabilityId,
        id: `pp_${Date.now()}`,
        echo: inputObj,
      },
    };
  }

  const { token } = await readPayPalCredentials(invocation);

  switch (capabilityId) {
    case "paypal.create_invoice": {
      const recipientEmail = typeof inputObj.recipient_email === "string" && inputObj.recipient_email.trim()
        ? inputObj.recipient_email.trim()
        : isRecord(inputObj.primary_recipients) && Array.isArray(inputObj.primary_recipients)
        ? (inputObj.primary_recipients[0] as any)?.billing_info?.email_address
        : "";

      if (!recipientEmail) {
        throw new IntegrationRuntimeError("recipient_email is required.", {
          code: "INVALID_PAYPAL_INPUT",
          category: "validation",
          status: 400,
        });
      }

      const res = await fetch(`${PAYPAL_API_BASE}/v2/invoicing/invoices`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          detail: {
            currency_code: typeof inputObj.currency === "string" ? inputObj.currency : "USD",
            note: typeof inputObj.note === "string" ? inputObj.note : "Invoice generated by Nexus.",
          },
          primary_recipients: [
            {
              billing_info: {
                email_address: recipientEmail,
              },
            },
          ],
          items: Array.isArray(inputObj.items) ? inputObj.items : [
            {
              name: typeof inputObj.item_name === "string" ? inputObj.item_name : "Consulting Service",
              quantity: "1",
              unit_amount: {
                currency_code: typeof inputObj.currency === "string" ? inputObj.currency : "USD",
                value: typeof inputObj.amount === "string" ? inputObj.amount : "100.00",
              },
            },
          ],
        }),
        signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
      });

      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new IntegrationRuntimeError(data?.message || "Failed to create PayPal invoice.", {
          code: "PAYPAL_INVOICE_FAILED",
          category: "provider",
          status: res.status,
          details: data,
        });
      }

      return {
        success: true,
        responseStatus: res.status,
        providerRequestId: res.headers.get("paypal-debug-id") || null,
        rateLimit: null,
        metadata: data,
      };
    }

    case "paypal.issue_refund": {
      const captureId = inputObj.capture_id ?? inputObj.id;
      if (!captureId) {
        throw new IntegrationRuntimeError("capture_id is required.", {
          code: "INVALID_PAYPAL_INPUT",
          category: "validation",
          status: 400,
        });
      }

      const res = await fetch(`${PAYPAL_API_BASE}/v2/payments/captures/${encodeURIComponent(String(captureId))}/refund`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          amount: isRecord(inputObj.amount) ? inputObj.amount : undefined,
          note_to_payer: typeof inputObj.note === "string" ? inputObj.note : "Refund processed via Nexus.",
        }),
        signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
      });

      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new IntegrationRuntimeError(data?.message || "Failed to issue PayPal refund.", {
          code: "PAYPAL_REFUND_FAILED",
          category: "provider",
          status: res.status,
          details: data,
        });
      }

      return {
        success: true,
        responseStatus: res.status,
        providerRequestId: res.headers.get("paypal-debug-id") || null,
        rateLimit: null,
        metadata: data,
      };
    }

    case "paypal.capture_payment": {
      const authorizationId = inputObj.authorization_id ?? inputObj.id;
      if (!authorizationId) {
        throw new IntegrationRuntimeError("authorization_id is required.", {
          code: "INVALID_PAYPAL_INPUT",
          category: "validation",
          status: 400,
        });
      }

      const res = await fetch(`${PAYPAL_API_BASE}/v2/payments/authorizations/${encodeURIComponent(String(authorizationId))}/capture`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          amount: isRecord(inputObj.amount) ? inputObj.amount : undefined,
          is_final_capture: Boolean(inputObj.is_final_capture ?? true),
        }),
        signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
      });

      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new IntegrationRuntimeError(data?.message || "Failed to capture PayPal payment.", {
          code: "PAYPAL_CAPTURE_FAILED",
          category: "provider",
          status: res.status,
          details: data,
        });
      }

      return {
        success: true,
        responseStatus: res.status,
        providerRequestId: res.headers.get("paypal-debug-id") || null,
        rateLimit: null,
        metadata: data,
      };
    }

    default:
      throw new IntegrationRuntimeError(`Unsupported capability: ${capabilityId}`, {
        code: "UNSUPPORTED_CAPABILITY",
        category: "validation",
        status: 400,
      });
  }
}

async function checkPayPalHealth(
  context: IntegrationRuntimeInvocationContext,
): Promise<IntegrationRuntimeHealthResult> {
  const started = Date.now();
  try {
    const creds = await context.credentials.read(["access_token"]);
    const token = creds.access_token;
    if (!token) {
      return {
        healthy: false,
        checkedAt: new Date().toISOString(),
        latencyMs: Date.now() - started,
        externalAccountId: null,
        externalAccountLabel: null,
        metadata: { reason: "Missing access token" },
      };
    }

    const res = await fetch(`${PAYPAL_API_BASE}/v1/identity/oauth2/userinfo?schema=paypalv1.1`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
      signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
    });

    const data = await res.json().catch(() => ({}));
    const latency = Date.now() - started;
    const name = isRecord(data) && typeof data.name === "string" ? data.name : "PayPal Business";
    const payerId = isRecord(data) && typeof data.payer_id === "string" ? data.payer_id : "paypal_merchant";

    return {
      healthy: res.ok,
      checkedAt: new Date().toISOString(),
      latencyMs: latency,
      externalAccountId: payerId,
      externalAccountLabel: name,
      metadata: { status: res.status },
    };
  } catch (err: unknown) {
    return {
      healthy: false,
      checkedAt: new Date().toISOString(),
      latencyMs: Date.now() - started,
      externalAccountId: null,
      externalAccountLabel: null,
      metadata: { reason: err instanceof Error ? err.message : "PayPal health check failed." },
    };
  }
}

export const PAYPAL_RUNTIME_ADAPTER: IntegrationConnectorRuntimeAdapter = {
  manifest: {
    schemaVersion: INTEGRATION_RUNTIME_SCHEMA_VERSION,
    adapterId: "j10.paypal.runtime",
    adapterVersion: "1.0.0",
    providerId: "paypal",
    state: "installed",
    authType: "oauth2",
    environments: ["development", "production"],
    modes: ["simulate", "sandbox", "live"],
    capabilities: [
      "paypal.create_invoice",
      "paypal.issue_refund",
      "paypal.capture_payment",
    ].map((capabilityId) => ({
      capabilityId,
      kind: "action" as const,
      modes: ["simulate", "sandbox", "live"] as const,
      requiredScopes: [],
      supportsIdempotency: true,
    })),
    supportsHealthChecks: true,
    supportsTokenRefresh: false,
    supportsTokenRevocation: false,
    requestTimeoutMs: REQUEST_TIMEOUT_MS,
    maxConcurrency: 10,
  },
  healthCheck: checkPayPalHealth,
  executeAction: executePayPalAction,
};
